// GENERATED by node tools/codegen/face.mjs — DO NOT EDIT.
// Source of truth: client-3d/src/assets/faceKit/face-kit.js
//   (polygon-forge face kit style order + palettes) and the atlases in
//   client-3d/public/assets/face-kit/assets/.

export type FaceStyleId = "stoic" | "rogue" | "youth" | "ghost" | "sharp" | "feral" | "regal" | "veteran";

/** Registry-record / creator face shape (camelCase like skinTone/hairMat). */
export interface CharacterFaceConfig {
  eyes: FaceStyleId;
  brows: FaceStyleId;
  nose: FaceStyleId;
  mouth: FaceStyleId;
  eyeColor: string;
  browColor: string;
  lipColor: string;
}

export const FACE_STYLE_IDS: readonly FaceStyleId[] = ["stoic","rogue","youth","ghost","sharp","feral","regal","veteran"];

export const FACE_STYLE_LABELS: Readonly<Record<FaceStyleId, string>> = {
  "stoic": "PS2 Natural",
  "rogue": "Western Toon",
  "youth": "Anime Hero",
  "ghost": "Chibi Adventure",
  "sharp": "Graphic Novel",
  "feral": "Arcade Fighter",
  "regal": "Painterly Noble",
  "veteran": "Wasteland Veteran"
};

export const FACE_EYE_COLORS: readonly string[] = ["#7eb7c7","#78955e","#7b573b","#b7aa72","#4c5261","#b7d4dd"];
export const FACE_BROW_COLORS: readonly string[] = ["#171313","#35241e","#5b3827","#8a5b38","#b58b5b","#77716b"];
export const FACE_LIP_COLORS: readonly string[] = ["#74443f","#94544f","#ae6d68","#6c3438","#b77a72","#4f302e"];

/** Canonical creator draft face — every new character starts here. */
export const DEFAULT_FACE: Readonly<CharacterFaceConfig> = Object.freeze({
  eyes: "stoic",
  brows: "stoic",
  nose: "stoic",
  mouth: "stoic",
  eyeColor: "#7eb7c7",
  browColor: "#171313",
  lipColor: "#74443f",
});

const faceStyleIdSet: ReadonlySet<string> = new Set(FACE_STYLE_IDS);

export function isFaceStyleId(value: unknown): value is FaceStyleId {
  return typeof value === "string" && faceStyleIdSet.has(value);
}
