// GENERATED by node tools/codegen/wardrobe.mjs — DO NOT EDIT.
// Source of truth: client-3d/public/assets/pawn-pack/equipment/
//   manifest.json + wardrobe_palette.json + ClothingMaterials/clothing_materials.json

export interface WardrobeZoneGen {
  key: string;
  family: string;
  slots: readonly string[];
  default: string;
}

export interface WardrobePieceGen {
  id: string;
  name: string;
  slot: WardrobeSlot;
  group: string;
  zones: readonly WardrobeZoneGen[];
}

export interface WardrobeSwatchGen {
  id: string;
  name: string;
  hex: string;
}

export const WARDROBE_SLOTS = ["under_full","under_torso","under_legs","under_feet","under_hands"] as const;
export type WardrobeSlot = typeof WARDROBE_SLOTS[number];

export const WARDROBE_PIECES: readonly WardrobePieceGen[] = [
  {
    "id": "under_bodysuit",
    "name": "Bodysuit",
    "slot": "under_full",
    "group": "Underlayer",
    "zones": [
      {
        "key": "suit",
        "family": "workcloth",
        "slots": [
          "PF2_Cloth"
        ],
        "default": "#89cff0"
      }
    ]
  },
  {
    "id": "top_rigged_tank",
    "name": "Rigged Canvas Tank",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c3"
        ],
        "default": "#b08040"
      },
      {
        "key": "straps",
        "family": "workcloth",
        "slots": [
          "c5"
        ],
        "default": "#406090"
      }
    ]
  },
  {
    "id": "top_frayed_tunic",
    "name": "Frayed Work Tunic",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#806040"
      }
    ]
  },
  {
    "id": "top_plated_rig_vest",
    "name": "Plated Chest-Rig Vest",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "plates",
        "family": "leather",
        "slots": [
          "c5"
        ],
        "default": "#b08040"
      },
      {
        "key": "vest",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#303030"
      },
      {
        "key": "collar",
        "family": "workcloth",
        "slots": [
          "c3"
        ],
        "default": "#908060"
      }
    ]
  },
  {
    "id": "top_padded_leather_vest",
    "name": "Padded Leather Vest",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "body",
        "family": "leather",
        "slots": [
          "c0"
        ],
        "default": "#806040"
      },
      {
        "key": "padding",
        "family": "rubber",
        "slots": [
          "c1"
        ],
        "default": "#303020"
      }
    ]
  },
  {
    "id": "top_spiked_leather_vest",
    "name": "Spiked Leather Vest",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "panels",
        "family": "leather",
        "slots": [
          "c1"
        ],
        "default": "#b08040"
      },
      {
        "key": "sides",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#806040"
      }
    ]
  },
  {
    "id": "top_reinforced_crop_vest",
    "name": "Reinforced Crop Vest",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "plates",
        "family": "workcloth",
        "slots": [
          "c3"
        ],
        "default": "#908070"
      },
      {
        "key": "shoulders",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#303030"
      },
      {
        "key": "hem",
        "family": "workcloth",
        "slots": [
          "c4"
        ],
        "default": "#606060"
      }
    ]
  },
  {
    "id": "top_scrap_plate_tunic",
    "name": "Scrap-Plate Tunic",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#b08040"
      },
      {
        "key": "scraps",
        "family": "workcloth",
        "slots": [
          "c4"
        ],
        "default": "#908060"
      },
      {
        "key": "trim",
        "family": "leather",
        "slots": [
          "c2"
        ],
        "default": "#806040"
      }
    ]
  },
  {
    "id": "top_laced_corset_vest",
    "name": "Laced Corset Vest",
    "slot": "under_torso",
    "group": "Tops",
    "zones": [
      {
        "key": "tunic",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#b08040"
      },
      {
        "key": "wrap",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#406090"
      },
      {
        "key": "corset",
        "family": "leather",
        "slots": [
          "c0"
        ],
        "default": "#303030"
      }
    ]
  },
  {
    "id": "legs_wrapped_workpants",
    "name": "Wrapped Workpants",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#804040"
      },
      {
        "key": "wrap",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#505060"
      },
      {
        "key": "guard",
        "family": "leather",
        "slots": [
          "c5"
        ],
        "default": "#706050"
      }
    ]
  },
  {
    "id": "legs_reinforced_denim_pants",
    "name": "Reinforced Denim Pants",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#804040"
      },
      {
        "key": "guards",
        "family": "rubber",
        "slots": [
          "c1"
        ],
        "default": "#505050"
      }
    ]
  },
  {
    "id": "legs_plated_trousers",
    "name": "Plated Combat Trousers",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#804040"
      },
      {
        "key": "shells",
        "family": "rubber",
        "slots": [
          "c2"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "legs_layered_shorts",
    "name": "Layered Combat Shorts",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "shorts",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#505060"
      },
      {
        "key": "wraps",
        "family": "workcloth",
        "slots": [
          "c1",
          "c3"
        ],
        "default": "#908070"
      },
      {
        "key": "bands",
        "family": "workcloth",
        "slots": [
          "c4"
        ],
        "default": "#804040"
      }
    ]
  },
  {
    "id": "legs_strapped_trousers",
    "name": "Strapped Utility Trousers",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#804040"
      },
      {
        "key": "guards",
        "family": "rubber",
        "slots": [
          "c3"
        ],
        "default": "#406090"
      },
      {
        "key": "straps",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#303030"
      }
    ]
  },
  {
    "id": "legs_skirted_workpants",
    "name": "Skirted Workpants",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#804040"
      },
      {
        "key": "skirt",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#505060"
      },
      {
        "key": "belt",
        "family": "leather",
        "slots": [
          "c3"
        ],
        "default": "#406090"
      }
    ]
  },
  {
    "id": "legs_gaitered_cargo_pants",
    "name": "Gaitered Cargo Pants",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#804040"
      },
      {
        "key": "gaiters",
        "family": "workcloth",
        "slots": [
          "c4"
        ],
        "default": "#908060"
      }
    ]
  },
  {
    "id": "legs_padded_canvas_trousers",
    "name": "Padded Canvas Trousers",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#804040"
      },
      {
        "key": "wrap",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#505060"
      }
    ]
  },
  {
    "id": "legs_sashed_patrol_pants",
    "name": "Sashed Patrol Pants",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "pants",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#804040"
      },
      {
        "key": "sash",
        "family": "workcloth",
        "slots": [
          "c3"
        ],
        "default": "#605040"
      },
      {
        "key": "straps",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#406090"
      }
    ]
  },
  {
    "id": "legs_layered_wrap_skirt",
    "name": "Layered Wrap Skirt",
    "slot": "under_legs",
    "group": "Bottoms",
    "zones": [
      {
        "key": "skirt",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#804040"
      },
      {
        "key": "straps",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#406090"
      },
      {
        "key": "guards",
        "family": "rubber",
        "slots": [
          "c5"
        ],
        "default": "#505060"
      }
    ]
  },
  {
    "id": "boots_canvas_ankle",
    "name": "Canvas Ankle Boots",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#303030"
      },
      {
        "key": "panels",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "boots_layered_sneakers",
    "name": "Layered Street Sneakers",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "panels",
        "family": "leather",
        "slots": [
          "c1"
        ],
        "default": "#505050"
      },
      {
        "key": "vamp",
        "family": "workcloth",
        "slots": [
          "c3"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "boots_split_toe",
    "name": "Split-Toe Boots",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "upper",
        "family": "leather",
        "slots": [
          "c0"
        ],
        "default": "#908070"
      },
      {
        "key": "vamp",
        "family": "workcloth",
        "slots": [
          "c3"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "boots_trail_shoes",
    "name": "Rugged Trail Shoes",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c5"
        ],
        "default": "#808080"
      },
      {
        "key": "tongue",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#303030"
      }
    ]
  },
  {
    "id": "boots_double_strap",
    "name": "Double-Strap Boots",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "straps",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#303030"
      },
      {
        "key": "cuff",
        "family": "leather",
        "slots": [
          "c3"
        ],
        "default": "#406090"
      }
    ]
  },
  {
    "id": "boots_rubberized_canvas",
    "name": "Rubberized Canvas Boots",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#303030"
      },
      {
        "key": "collar",
        "family": "workcloth",
        "slots": [
          "c3"
        ],
        "default": "#706050"
      }
    ]
  },
  {
    "id": "boots_toe_capped",
    "name": "Toe-Capped Work Boots",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "upper",
        "family": "leather",
        "slots": [
          "c0"
        ],
        "default": "#303030"
      }
    ]
  },
  {
    "id": "boots_combat_sneakers",
    "name": "Combat Sneakers",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "upper",
        "family": "leather",
        "slots": [
          "c2"
        ],
        "default": "#303030"
      },
      {
        "key": "laces",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "boots_cuffed_runners",
    "name": "Cuffed Runners",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "cuff",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#303030"
      },
      {
        "key": "vamp",
        "family": "leather",
        "slots": [
          "c3"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "boots_reinforced_street",
    "name": "Reinforced Street Boots",
    "slot": "under_feet",
    "group": "Footwear",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#303030"
      },
      {
        "key": "collar",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "gloves_knuckled_half",
    "name": "Knuckled Half-Gloves",
    "slot": "under_hands",
    "group": "Gloves",
    "zones": [
      {
        "key": "cuff",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#406090"
      },
      {
        "key": "knuckle",
        "family": "rubber",
        "slots": [
          "c2"
        ],
        "default": "#808080"
      }
    ]
  },
  {
    "id": "gloves_guarded_leather",
    "name": "Guarded Leather Gloves",
    "slot": "under_hands",
    "group": "Gloves",
    "zones": [
      {
        "key": "body",
        "family": "leather",
        "slots": [
          "c0"
        ],
        "default": "#a07040"
      },
      {
        "key": "knuckle",
        "family": "rubber",
        "slots": [
          "c3"
        ],
        "default": "#406090"
      }
    ]
  },
  {
    "id": "gloves_plain_work",
    "name": "Plain Work Gloves",
    "slot": "under_hands",
    "group": "Gloves",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#a07040"
      }
    ]
  },
  {
    "id": "gloves_reinforced_knit",
    "name": "Reinforced Knit Gloves",
    "slot": "under_hands",
    "group": "Gloves",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#808080"
      },
      {
        "key": "cuff",
        "family": "workcloth",
        "slots": [
          "c2"
        ],
        "default": "#406090"
      },
      {
        "key": "knuckle",
        "family": "rubber",
        "slots": [
          "c4"
        ],
        "default": "#a07040"
      }
    ]
  },
  {
    "id": "gloves_light_utility",
    "name": "Light Utility Gloves",
    "slot": "under_hands",
    "group": "Gloves",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#605090"
      },
      {
        "key": "cuff",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#908070"
      }
    ]
  },
  {
    "id": "gloves_tipped_work",
    "name": "Tipped Work Gloves",
    "slot": "under_hands",
    "group": "Gloves",
    "zones": [
      {
        "key": "body",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#a07040"
      },
      {
        "key": "cuff",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#303030"
      }
    ]
  },
  {
    "id": "gloves_plated_handwraps",
    "name": "Plated Hand-Wraps",
    "slot": "under_hands",
    "group": "Gloves",
    "zones": [
      {
        "key": "cuff",
        "family": "workcloth",
        "slots": [
          "c0"
        ],
        "default": "#505050"
      },
      {
        "key": "wrap",
        "family": "workcloth",
        "slots": [
          "c1"
        ],
        "default": "#a07040"
      }
    ]
  }
];

export const WARDROBE_PALETTES: Readonly<Record<string, readonly WardrobeSwatchGen[]>> = {
  "workcloth": [
    {
      "id": "workcloth_rust",
      "name": "rust",
      "hex": "#804040"
    },
    {
      "id": "workcloth_clay",
      "name": "clay",
      "hex": "#7a5038"
    },
    {
      "id": "workcloth_sand",
      "name": "sand",
      "hex": "#a08858"
    },
    {
      "id": "workcloth_bone",
      "name": "bone",
      "hex": "#b0a890"
    },
    {
      "id": "workcloth_olive",
      "name": "olive",
      "hex": "#687048"
    },
    {
      "id": "workcloth_sage",
      "name": "sage",
      "hex": "#5f7358"
    },
    {
      "id": "workcloth_slate",
      "name": "slate",
      "hex": "#506078"
    },
    {
      "id": "workcloth_denim",
      "name": "denim",
      "hex": "#406090"
    },
    {
      "id": "workcloth_graphite",
      "name": "graphite",
      "hex": "#3a3a3e"
    },
    {
      "id": "workcloth_oxblood",
      "name": "oxblood",
      "hex": "#6e3a34"
    },
    {
      "id": "workcloth_mustard",
      "name": "mustard",
      "hex": "#a08030"
    },
    {
      "id": "workcloth_teal",
      "name": "teal",
      "hex": "#3f7472"
    }
  ],
  "leather": [
    {
      "id": "leather_tan",
      "name": "tan",
      "hex": "#b08040"
    },
    {
      "id": "leather_saddle",
      "name": "saddle",
      "hex": "#806040"
    },
    {
      "id": "leather_umber",
      "name": "umber",
      "hex": "#5f4630"
    },
    {
      "id": "leather_oxblood",
      "name": "oxblood",
      "hex": "#6b3b30"
    },
    {
      "id": "leather_char",
      "name": "char",
      "hex": "#34302c"
    },
    {
      "id": "leather_ash",
      "name": "ash",
      "hex": "#7a7468"
    },
    {
      "id": "leather_olive_tan",
      "name": "olive_tan",
      "hex": "#6f6844"
    },
    {
      "id": "leather_mahogany",
      "name": "mahogany",
      "hex": "#7e4a38"
    },
    {
      "id": "leather_forest",
      "name": "forest",
      "hex": "#4c5f46"
    },
    {
      "id": "leather_indigo",
      "name": "indigo",
      "hex": "#46506e"
    }
  ],
  "rubber": [
    {
      "id": "rubber_black",
      "name": "black",
      "hex": "#303030"
    },
    {
      "id": "rubber_gunmetal",
      "name": "gunmetal",
      "hex": "#4a4a4e"
    },
    {
      "id": "rubber_olive",
      "name": "olive",
      "hex": "#4f5244"
    },
    {
      "id": "rubber_brick",
      "name": "brick",
      "hex": "#71453c"
    },
    {
      "id": "rubber_sand",
      "name": "sand",
      "hex": "#8a7f66"
    },
    {
      "id": "rubber_navy",
      "name": "navy",
      "hex": "#3c4456"
    }
  ]
};

export const HAIR_STYLES: readonly { id: string; name: string }[] = [
  {
    "id": "hair_mop",
    "name": "Mop Top"
  },
  {
    "id": "hair_afro2",
    "name": "Afro"
  },
  {
    "id": "hair_crop2",
    "name": "Short Crop"
  },
  {
    "id": "hair_banded_mohawk",
    "name": "Banded Mohawk"
  },
  {
    "id": "hair_spiked_topknot",
    "name": "Spiked Topknot"
  },
  {
    "id": "hair_twin_pigtails",
    "name": "Twin Pigtails"
  },
  {
    "id": "hair_swept_spikes",
    "name": "Swept Spikes"
  },
  {
    "id": "hair_short_ponytail",
    "name": "Short Ponytail"
  },
  {
    "id": "hair_spiked_mohawk",
    "name": "Spiked Mohawk"
  },
  {
    "id": "hair_flared_wings",
    "name": "Flared Wings"
  },
  {
    "id": "hair_low_tufts",
    "name": "Low Tufts"
  },
  {
    "id": "hair_swept_bob",
    "name": "Swept Bob"
  },
  {
    "id": "hair_braided_crown",
    "name": "Braided Crown"
  },
  {
    "id": "hair_ridge_mohawk",
    "name": "Ridge Mohawk"
  },
  {
    "id": "hair_side_ponytail",
    "name": "Side Ponytail"
  },
  {
    "id": "hair_split_mohawk",
    "name": "Split Mohawk"
  },
  {
    "id": "hair_fauxhawk",
    "name": "Fauxhawk"
  },
  {
    "id": "hair_slicked_crop",
    "name": "Slicked Crop"
  },
  {
    "id": "hair_side_sweep",
    "name": "Side Sweep"
  },
  {
    "id": "hair_flared_shag",
    "name": "Flared Shag"
  },
  {
    "id": "hair_cropped_buzz",
    "name": "Cropped Buzz"
  },
  {
    "id": "hair_messy_crop",
    "name": "Messy Crop"
  },
  {
    "id": "hair_textured_crop",
    "name": "Textured Crop"
  },
  {
    "id": "hair_shoulder_shag",
    "name": "Shoulder Shag"
  },
  {
    "id": "hair_messy_side_part",
    "name": "Messy Side-Part"
  },
  {
    "id": "hair_flat_top",
    "name": "Flat Top"
  },
  {
    "id": "hair_top_patch",
    "name": "Top Patch"
  }
];

export const HAIR_COLORS: readonly { id: string; name: string; hex: string }[] = [
  {
    "id": "hair_raven",
    "name": "Raven black",
    "hex": "#1d1b22"
  },
  {
    "id": "hair_ink",
    "name": "Ink blue-black",
    "hex": "#232134"
  },
  {
    "id": "hair_umber",
    "name": "Dark umber",
    "hex": "#3a2a1a"
  },
  {
    "id": "hair_chestnut",
    "name": "Chestnut",
    "hex": "#5a3a22"
  },
  {
    "id": "hair_ash_blonde",
    "name": "Ash blonde",
    "hex": "#b3a077"
  },
  {
    "id": "hair_silver",
    "name": "Silver",
    "hex": "#b9bcc4"
  },
  {
    "id": "hair_crimson",
    "name": "Crimson",
    "hex": "#7a2330"
  },
  {
    "id": "hair_auburn",
    "name": "Auburn",
    "hex": "#6e3a24"
  },
  {
    "id": "hair_honey",
    "name": "Honey",
    "hex": "#9a7440"
  },
  {
    "id": "hair_steel",
    "name": "Steel gray",
    "hex": "#7c8088"
  },
  {
    "id": "hair_moss",
    "name": "Moss",
    "hex": "#4f6842"
  },
  {
    "id": "hair_teal",
    "name": "Teal",
    "hex": "#2f5f5c"
  },
  {
    "id": "hair_violet",
    "name": "Violet",
    "hex": "#544060"
  },
  {
    "id": "hair_rose",
    "name": "Faded rose",
    "hex": "#9c6670"
  },
  {
    "id": "hair_bleach",
    "name": "Bleach",
    "hex": "#d8d2c0"
  }
];

const piecesById = new Map(WARDROBE_PIECES.map((piece) => [piece.id, piece]));
const swatchHexesByFamily = new Map(
  Object.entries(WARDROBE_PALETTES).map(([family, swatches]) => [family, new Set(swatches.map((swatch) => swatch.hex))]),
);

export function wardrobePieceById(id: string): WardrobePieceGen | null {
  return piecesById.get(id) ?? null;
}

/** True when `hex` is a legal choice for the zone: family swatch or the authored default. */
export function wardrobeZoneColorAllowed(zone: WardrobeZoneGen, hex: string): boolean {
  const normalized = hex.trim().toLowerCase();
  if (normalized === zone.default) return true;
  return swatchHexesByFamily.get(zone.family)?.has(normalized) ?? false;
}
