#!/usr/bin/env node
// face.mjs — generate the face registry modules from the vendored face kit.
//
// Source of truth: client-3d/src/assets/faceKit/face-kit.js (polygon-forge
// face kit runtime — style order and palette constants) plus the atlas set
// under client-3d/public/assets/face-kit/assets/.
// Emits identical generated modules for the two consumers that cannot share
// a package boundary:
//   server/src/game/face.gen.ts        (creation validation)
//   client-3d/src/assets/face.gen.ts   (creator catalog + doll defaults)
//
// Usage: node tools/codegen/face.mjs [--check]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..", "..");
const kitModulePath = path.join(repoRoot, "client-3d", "src", "assets", "faceKit", "face-kit.js");
const atlasDir = path.join(repoRoot, "client-3d", "public", "assets", "face-kit", "assets");
const outputs = [
  path.join(repoRoot, "server", "src", "game", "face.gen.ts"),
  path.join(repoRoot, "client-3d", "src", "assets", "face.gen.ts"),
];
const regenCommand = "node tools/codegen/face.mjs";

const check = process.argv.includes("--check");
const hexPattern = /^#[0-9a-f]{6}$/u;
const styleIdPattern = /^[a-z][a-z0-9_]{1,32}$/u;

const kit = await import(pathToFileURL(kitModulePath).href);
const failures = [];

const styleIds = Array.isArray(kit.FACE_STYLE_ORDER) ? [...kit.FACE_STYLE_ORDER] : [];
if (styleIds.length === 0) failures.push("kit exports no FACE_STYLE_ORDER styles");
for (const id of styleIds) {
  if (!styleIdPattern.test(String(id))) failures.push(`bad face style id: ${String(id)}`);
}
const labels = kit.FACE_STYLE_LABELS ?? {};
for (const id of styleIds) {
  if (typeof labels[id] !== "string" || labels[id].length === 0) failures.push(`missing label for style ${id}`);
}

function palette(name) {
  const values = kit[name];
  if (!Array.isArray(values) || values.length === 0) {
    failures.push(`kit exports no ${name}`);
    return [];
  }
  const out = [];
  for (const value of values) {
    const hex = String(value).trim().toLowerCase();
    if (!hexPattern.test(hex)) failures.push(`${name}: bad hex ${String(value)}`);
    else if (!out.includes(hex)) out.push(hex);
  }
  return out;
}

const eyeColors = palette("EYE_COLORS");
const browColors = palette("BROW_COLORS");
const lipColors = palette("LIP_COLORS");

for (const file of Object.values(kit.FACE_ASSET_FILES ?? {})) {
  if (!fs.existsSync(path.join(atlasDir, path.basename(String(file))))) {
    failures.push(`atlas missing under public assets: ${String(file)}`);
  }
}

if (failures.length > 0) {
  console.error(`face codegen: ${failures.length} failure(s)`);
  for (const failure of failures) console.error(`  - ${failure}`);
  process.exit(1);
}

const banner = `// GENERATED by ${regenCommand} — DO NOT EDIT.\n`
  + "// Source of truth: client-3d/src/assets/faceKit/face-kit.js\n"
  + "//   (polygon-forge face kit style order + palettes) and the atlases in\n"
  + "//   client-3d/public/assets/face-kit/assets/.\n";

const union = styleIds.map((id) => JSON.stringify(id)).join(" | ");
const body = `${banner}
export type FaceStyleId = ${union};

/** Registry-record / creator face shape (camelCase like skinTone/hairMat). */
export interface CharacterFaceConfig {
  eyes: FaceStyleId;
  brows: FaceStyleId;
  nose: FaceStyleId;
  mouth: FaceStyleId;
  eyeColor: string;
  browColor: string;
  lipColor: string;
}

export const FACE_STYLE_IDS: readonly FaceStyleId[] = ${JSON.stringify(styleIds)};

export const FACE_STYLE_LABELS: Readonly<Record<FaceStyleId, string>> = ${JSON.stringify(
  Object.fromEntries(styleIds.map((id) => [id, labels[id]])), null, 2)};

export const FACE_EYE_COLORS: readonly string[] = ${JSON.stringify(eyeColors)};
export const FACE_BROW_COLORS: readonly string[] = ${JSON.stringify(browColors)};
export const FACE_LIP_COLORS: readonly string[] = ${JSON.stringify(lipColors)};

/** Canonical creator draft face — every new character starts here. */
export const DEFAULT_FACE: Readonly<CharacterFaceConfig> = Object.freeze({
  eyes: ${JSON.stringify(styleIds[0])},
  brows: ${JSON.stringify(styleIds[0])},
  nose: ${JSON.stringify(styleIds[0])},
  mouth: ${JSON.stringify(styleIds[0])},
  eyeColor: ${JSON.stringify(eyeColors[0])},
  browColor: ${JSON.stringify(browColors[0])},
  lipColor: ${JSON.stringify(lipColors[0])},
});

const faceStyleIdSet: ReadonlySet<string> = new Set(FACE_STYLE_IDS);

export function isFaceStyleId(value: unknown): value is FaceStyleId {
  return typeof value === "string" && faceStyleIdSet.has(value);
}
`;

let stale = false;
for (const output of outputs) {
  const current = fs.existsSync(output) ? fs.readFileSync(output, "utf8") : null;
  if (current !== body) {
    stale = true;
    if (!check) {
      fs.mkdirSync(path.dirname(output), { recursive: true });
      fs.writeFileSync(output, body);
      console.log(`face codegen: wrote ${path.relative(repoRoot, output)}`);
    } else {
      console.error(`face codegen: STALE ${path.relative(repoRoot, output)} — run: ${regenCommand}`);
    }
  }
}

if (check) {
  process.exit(stale ? 1 : 0);
} else if (!stale) {
  console.log("face codegen: outputs already fresh");
} else {
  console.log(`face codegen: ${styleIds.length} styles, ${eyeColors.length}/${browColors.length}/${lipColors.length} eye/brow/lip colors`);
}
