#!/usr/bin/env node
// wardrobe.mjs — generate the wardrobe registry modules from the pawn-pack.
//
// Source of truth: client-3d/public/assets/pawn-pack/equipment/
//   manifest.json                 (items + palette zones; group Hair = styles)
//   wardrobe_palette.json         (dye families + swatches)
//   ClothingMaterials/clothing_materials.json (hair_* color presets)
// Emits identical generated modules for the two consumers that cannot share
// a package boundary:
//   server/src/game/wardrobe.gen.ts       (creation validation)
//   client-3d/src/assets/wardrobe.gen.ts  (creator catalog)
//
// Usage: node tools/codegen/wardrobe.mjs [--check]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..", "..");
const equipmentDir = path.join(repoRoot, "client-3d", "public", "assets", "pawn-pack", "equipment");
const manifestPath = path.join(equipmentDir, "manifest.json");
const palettePath = path.join(equipmentDir, "wardrobe_palette.json");
const clothingMaterialsPath = path.join(equipmentDir, "ClothingMaterials", "clothing_materials.json");
const outputs = [
  path.join(repoRoot, "server", "src", "game", "wardrobe.gen.ts"),
  path.join(repoRoot, "client-3d", "src", "assets", "wardrobe.gen.ts"),
];
const regenCommand = "node tools/codegen/wardrobe.mjs";

const WARDROBE_SLOTS = ["under_full", "under_torso", "under_legs", "under_feet", "under_hands"];
const hairIdPattern = /^hair_[a-z0-9_]{1,64}$/u;
const hexPattern = /^#[0-9a-f]{6}$/u;

const check = process.argv.includes("--check");

const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
const paletteFile = JSON.parse(fs.readFileSync(palettePath, "utf8"));
const clothingMaterials = JSON.parse(fs.readFileSync(clothingMaterialsPath, "utf8"));

const failures = [];

const palettes = {};
for (const [family, spec] of Object.entries(paletteFile.palettes)) {
  if (family === "hair") continue; // hair colors ship as clothing-material presets
  palettes[family] = spec.swatches.map((swatch) => {
    const hex = String(swatch.hex ?? swatch[1] ?? "").toLowerCase();
    const name = String(swatch.name ?? swatch[0] ?? "");
    if (!hexPattern.test(hex)) failures.push(`palette ${family}/${name}: bad hex ${hex}`);
    return { id: `${family}_${name}`, name, hex };
  });
}

const pieces = [];
const hairStyles = [];
for (const item of manifest.items) {
  if (item.viewerOnly === true) continue;
  if (item.group === "Hair") {
    if (!hairIdPattern.test(item.id)) failures.push(`hair id fails pattern: ${item.id}`);
    if (item.slot !== "cranium") failures.push(`hair ${item.id}: slot must be cranium, got ${item.slot}`);
    hairStyles.push({ id: item.id, name: item.name });
    continue;
  }
  if (!item.palette || !WARDROBE_SLOTS.includes(item.slot)) continue;
  const zones = (item.palette.zones ?? []).map((zone) => {
    const family = String(zone.family ?? "");
    if (!palettes[family]) failures.push(`piece ${item.id}: unknown family ${family}`);
    const fallback = String(zone.default ?? "").toLowerCase();
    if (!hexPattern.test(fallback)) failures.push(`piece ${item.id}/${zone.key}: bad default ${fallback}`);
    return {
      key: String(zone.key ?? ""),
      family,
      slots: (zone.slots ?? []).map(String),
      default: fallback,
    };
  });
  if (zones.length < 1 || zones.length > 3) failures.push(`piece ${item.id}: ${zones.length} zones (must be 1-3)`);
  pieces.push({ id: item.id, name: item.name, slot: item.slot, group: item.group, zones });
}

const hairColors = clothingMaterials.materials
  .filter((material) => material.id.startsWith("hair_") && typeof material.color === "string")
  .map((material) => {
    const hex = material.color.toLowerCase();
    if (!hexPattern.test(hex)) failures.push(`hair color ${material.id}: bad hex ${hex}`);
    return { id: material.id, name: material.name ?? material.id, hex };
  });

if (pieces.length === 0) failures.push("no wardrobe pieces found in manifest");
if (hairStyles.length === 0) failures.push("no hair styles found in manifest");
if (hairColors.length === 0) failures.push("no hair_* color presets found");
for (const slot of WARDROBE_SLOTS) {
  if (!pieces.some((piece) => piece.slot === slot)) failures.push(`no pieces for slot ${slot}`);
}

if (failures.length > 0) {
  console.error(`wardrobe codegen failed:\n  - ${failures.join("\n  - ")}`);
  process.exit(1);
}

const banner = `// GENERATED by ${regenCommand} — DO NOT EDIT.\n`
  + "// Source of truth: client-3d/public/assets/pawn-pack/equipment/\n"
  + "//   manifest.json + wardrobe_palette.json + ClothingMaterials/clothing_materials.json\n";

const body = `${banner}
export interface WardrobeZoneGen {
  key: string;
  family: string;
  slots: readonly string[];
  default: string;
}

export interface WardrobePieceGen {
  id: string;
  name: string;
  slot: WardrobeSlot;
  group: string;
  zones: readonly WardrobeZoneGen[];
}

export interface WardrobeSwatchGen {
  id: string;
  name: string;
  hex: string;
}

export const WARDROBE_SLOTS = ${JSON.stringify(WARDROBE_SLOTS)} as const;
export type WardrobeSlot = typeof WARDROBE_SLOTS[number];

export const WARDROBE_PIECES: readonly WardrobePieceGen[] = ${JSON.stringify(pieces, null, 2)};

export const WARDROBE_PALETTES: Readonly<Record<string, readonly WardrobeSwatchGen[]>> = ${JSON.stringify(palettes, null, 2)};

export const HAIR_STYLES: readonly { id: string; name: string }[] = ${JSON.stringify(hairStyles, null, 2)};

export const HAIR_COLORS: readonly { id: string; name: string; hex: string }[] = ${JSON.stringify(hairColors, null, 2)};

const piecesById = new Map(WARDROBE_PIECES.map((piece) => [piece.id, piece]));
const swatchHexesByFamily = new Map(
  Object.entries(WARDROBE_PALETTES).map(([family, swatches]) => [family, new Set(swatches.map((swatch) => swatch.hex))]),
);

export function wardrobePieceById(id: string): WardrobePieceGen | null {
  return piecesById.get(id) ?? null;
}

/** True when \`hex\` is a legal choice for the zone: family swatch or the authored default. */
export function wardrobeZoneColorAllowed(zone: WardrobeZoneGen, hex: string): boolean {
  const normalized = hex.trim().toLowerCase();
  if (normalized === zone.default) return true;
  return swatchHexesByFamily.get(zone.family)?.has(normalized) ?? false;
}
`;

let stale = false;
for (const output of outputs) {
  const existing = fs.existsSync(output) ? fs.readFileSync(output, "utf8") : null;
  if (existing !== body) {
    stale = true;
    if (!check) {
      fs.writeFileSync(output, body, "utf8");
      console.log(`wrote ${path.relative(repoRoot, output)}`);
    } else {
      console.error(`stale: ${path.relative(repoRoot, output)} (run ${regenCommand})`);
    }
  }
}

if (check) {
  if (stale) process.exit(1);
  console.log(`wardrobe codegen check passed: ${pieces.length} pieces, ${hairStyles.length} hair styles, ${hairColors.length} hair colors`);
} else if (!stale) {
  console.log("wardrobe codegen: outputs already fresh");
} else {
  console.log(`wardrobe codegen: ${pieces.length} pieces, ${hairStyles.length} hair styles, ${hairColors.length} hair colors`);
}
