//! Authority construction, actor, and command rejection errors.

use super::*;

#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum SliceAuthorityBuildError {
    #[error("duplicate area id: {0}")]
    DuplicateArea(String),
    #[error("duplicate actor id: {0}")]
    DuplicateActor(String),
    #[error("duplicate population template id: {0}")]
    DuplicatePopulationTemplate(String),
    #[error("duplicate spawn zone id: {0}")]
    DuplicateSpawnZone(String),
    #[error("duplicate transition id: {0}")]
    DuplicateTransition(String),
    #[error("actor {actor_id} references unknown area {area_id}")]
    UnknownActorArea { actor_id: String, area_id: String },
    #[error("actor {actor_id} references unknown profession id {profession_id}")]
    UnknownActorProfessionId {
        actor_id: String,
        profession_id: String,
    },
    #[error("actor {actor_id} references unknown career goal id {career_goal_id}")]
    UnknownActorCareerGoalId {
        actor_id: String,
        career_goal_id: String,
    },
    #[error("population template {template_id} references unknown profession id {profession_id}")]
    UnknownPopulationProfessionId {
        template_id: String,
        profession_id: String,
    },
    #[error(
        "population template {template_id} references unknown career goal id {career_goal_id}"
    )]
    UnknownPopulationCareerGoalId {
        template_id: String,
        career_goal_id: String,
    },
    #[error("spawn zone {spawn_zone_id} references unknown population template {template_id}")]
    UnknownPopulationTemplate {
        spawn_zone_id: String,
        template_id: String,
    },
    #[error("spawn zone {spawn_zone_id} references unknown area {area_id}")]
    UnknownSpawnZoneArea {
        spawn_zone_id: String,
        area_id: String,
    },
    #[error("spawn zone {spawn_zone_id} cell is outside area {area_id}: {x},{y}")]
    SpawnZoneCellOutOfBounds {
        spawn_zone_id: String,
        area_id: String,
        x: i32,
        y: i32,
    },
    #[error("invalid population config: {0}")]
    InvalidPopulationConfig(String),
    #[error("invalid combat model: {0}")]
    InvalidCombatModel(String),
    #[error("combat tuning references unknown weapon id {weapon_id}")]
    UnknownCombatTuningWeaponId { weapon_id: String },
    #[error(
        "combat tuning range bands for {weapon_id} must satisfy 0 < pointBlank < ideal < max <= 96; got {point_blank_cells}/{ideal_cells}/{max_cells}"
    )]
    InvalidCombatTuningWeaponRangeBands {
        weapon_id: String,
        point_blank_cells: i32,
        ideal_cells: i32,
        max_cells: i32,
    },
    #[error("transition {transition_id} references unknown area {area_id}")]
    UnknownTransitionArea {
        transition_id: String,
        area_id: String,
    },
    #[error("transition {transition_id} cell is outside area {area_id}: {x},{y}")]
    TransitionOutOfBounds {
        transition_id: String,
        area_id: String,
        x: i32,
        y: i32,
    },
    #[error("transition {transition_id} destination is blocked in area {area_id}: {x},{y}")]
    TransitionDestinationBlocked {
        transition_id: String,
        area_id: String,
        x: i32,
        y: i32,
    },
    #[error("blocked cell references unknown area {area_id}")]
    UnknownBlockedCellArea { area_id: String },
    #[error("no-claim zone references unknown area {area_id}")]
    UnknownNoClaimZoneArea { area_id: String },
    #[error("clone facility {facility_id} references unknown area {area_id}")]
    UnknownCloneFacilityArea {
        facility_id: String,
        area_id: String,
    },
    #[error("clone facility {facility_id} respawn is outside area {area_id}: {x},{y}")]
    CloneFacilityOutOfBounds {
        facility_id: String,
        area_id: String,
        x: i32,
        y: i32,
    },
    #[error("ammo stockpile prop {prop_id} references unknown area {area_id}")]
    UnknownAmmoStockpileArea { prop_id: String, area_id: String },
    #[error("ammo stockpile prop {prop_id} cell is outside area {area_id}: {x},{y}")]
    AmmoStockpileOutOfBounds {
        prop_id: String,
        area_id: String,
        x: i32,
        y: i32,
    },
    #[error("exchange container prop {prop_id} references unknown area {area_id}")]
    UnknownExchangeContainerArea { prop_id: String, area_id: String },
    #[error("exchange container prop {prop_id} cell is outside area {area_id}: {x},{y}")]
    ExchangeContainerOutOfBounds {
        prop_id: String,
        area_id: String,
        x: i32,
        y: i32,
    },
    #[error("loot cache prop {prop_id} references unknown area {area_id}")]
    UnknownLootCacheArea { prop_id: String, area_id: String },
    #[error("loot cache prop {prop_id} cell is outside area {area_id}: {x},{y}")]
    LootCacheOutOfBounds {
        prop_id: String,
        area_id: String,
        x: i32,
        y: i32,
    },
    #[error("{field} must be an i32 integer")]
    InvalidCellCoordinate { field: &'static str },
}

#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum SliceAuthorityActorError {
    #[error("actor id is empty")]
    EmptyActorId,
    #[error("actor references unknown area {0}")]
    UnknownArea(String),
    #[error("actor spawn position is invalid for {0}")]
    InvalidPosition(String),
    #[error("actor spawn is outside area {area_id}: {x},{y}")]
    OutOfBounds { area_id: String, x: i32, y: i32 },
    #[error("actor spawn is blocked in area {area_id}: {x},{y}")]
    BlockedCell { area_id: String, x: i32, y: i32 },
    #[error("actor {actor_id} references unknown profession id {profession_id}")]
    UnknownProfessionId {
        actor_id: String,
        profession_id: String,
    },
    #[error("actor {actor_id} cannot use unavailable active title id {active_title_id}")]
    UnavailableActiveTitleId {
        actor_id: String,
        active_title_id: String,
    },
    #[error("actor {actor_id} references unknown career goal id {career_goal_id}")]
    UnknownCareerGoalId {
        actor_id: String,
        career_goal_id: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuthorityRejectReason {
    WrongSession,
    WrongPlayer,
    DuplicateCommand,
    UnknownActor,
    UnknownArea,
    InvalidMoveVector,
    InvalidMoveDuration,
    OutOfBounds,
    BlockedCell,
    UnknownTransition,
    WrongTransitionArea,
    NotAtTransitionTrigger,
    ActorNotAlive,
    ActorAsleep,
    PostureLocked,
    MeleeWhileKneeling,
    MoveCooldown,
    FireCooldown,
    NoWeaponEquipped,
    WeaponNotCertified,
    OutOfRange,
    LosBlocked,
    QueueFull,
    QueueEntryUnknown,
    InsufficientAction,
    EconomyCooldown,
    SampleCooldown,
    UnknownItem,
    ItemUnavailable,
    AmmoUnavailable,
    NotAtStockpile,
    UnknownEffect,
    NoCloneFacility,
    UnknownCloneFacility,
    InvalidCloneRespawn,
    InvalidResourceFamily,
    NotAtBankTerminal,
    InvalidBankQuantity,
    BankStackMissing,
    BankCapacity,
    BankOverflow,
    IngredientUnavailable,
    MissingSurveyTool,
    UnknownSchematic,
    ExtractorAlreadyPlaced,
    NoPlacedExtractor,
    NotExtractorOwner,
    NotAtExtractor,
    CampAlreadyPlaced,
    NoPlacedCamp,
    NotCampOwner,
    NotAtCamp,
    ExtractorHopperEmpty,
    ExtractorHopperFull,
    ExtractorBatteryPresent,
    MissingBattery,
    ExtractorBusy,
    InvalidExperimentation,
    TargetUnavailable,
    TargetProtected,
    TargetNotHarvestable,
    ContainerFull,
    LootOutOfRange,
    LootNoRights,
    LootNotLootable,
    LootMissingStack,
    LootInvalidQuantity,
    LootTargetUnknown,
    UnknownSkillBox,
    SkillAlreadyLearned,
    SkillNotLearned,
    SkillRequiredByLearnedBox,
    SkillPrerequisiteMissing,
    InsufficientProfessionXp,
    InsufficientCredits,
    InsufficientSkillPoints,
    TrainerUnavailable,
    CraftSessionActive,
    NoCraftSession,
    TradeSessionActive,
    NoTradeSession,
    TradeNotLocked,
    CraftSlotUnfilled,
    CraftSlotMismatch,
    CraftAlreadyAssembled,
    CraftNotAssembled,
    InvalidExperimentLine,
    InvalidCraftName,
    SchematicUsesExceeded,
    UnknownFactory,
    NotAtFactory,
    FactoryDraftMissing,
    FactoryDraftMismatch,
    ToolAlreadyHeld,
    StarterToolCooldown,
    UnknownProfessionTitle,
    UnknownCareerGoal,
    CannotGroupSelf,
    AlreadyInGroup,
    NotInGroup,
    NotGroupLeader,
    NotGroupMember,
    GroupFull,
    NoPendingInvite,
    CannotDuelSelf,
    AlreadyDueling,
    NoPendingDuelChallenge,
    NotAtPaTerminal,
    GuildNameTooLong,
    GuildTagTooLong,
    GuildNameExists,
    GuildTagExists,
    AlreadyInGuild,
    NotInGuild,
    NoGuildPermission,
    GuildNotFound,
    InviteExpired,
    InviteNotFound,
    InviteAlreadyPending,
    AlreadyWaring,
    NotWaring,
    NotInDuel,
    // Bio-Engineer (bioengineer-design.md §3.8): acquire / analyze / splice.
    UnknownCropSpecies,
    MissingGeneSampler,
    MissingGenomeScanner,
    MissingSpliceBench,
    GenomeUnavailable,
    SpliceSessionActive,
    NoSpliceSession,
    SpliceSlotMismatch,
    SpliceAlreadyAssembled,
    SpliceNotAssembled,
    InvalidSpliceLocus,
    InvalidSpliceExperiment,
    // ── Farming / land (agriculture-design.md §A.6) ──
    ParcelLimitReached,
    NotInHousingRegion,
    ParcelOverlap,
    TooCloseToPoi,
    TooCloseToRoad,
    /// Claim origin (snapped) fell inside a first-class no-claim zone (§B): the
    /// central hub square or another owner-configured lattice-aligned exclusion.
    NoClaimZone,
    UnknownParcel,
    NotParcelOwner,
    UpkeepNotDue,
    OutsideFarmYard,
    TileNotTilled,
    TileAlreadyTilled,
    TileOccupied,
    SeedNotOwned,
    StructureFootprintBlocked,
    NoFarmStructure,
    BuildCatalogUnknown,
    BuildOverlap,
    BuildNotOwner,
    // ── W4 Fertilize / W5 Harvest ──
    TileEmpty,
    TileAlreadyFertilized,
    CropNotMature,
}

impl AuthorityRejectReason {
    pub const fn code(self) -> &'static str {
        match self {
            Self::WrongSession => "wrong_session",
            Self::WrongPlayer => "wrong_player",
            Self::DuplicateCommand => "duplicate_command",
            Self::UnknownActor => "unknown_actor",
            Self::UnknownArea => "unknown_area",
            Self::InvalidMoveVector => "invalid_move_vector",
            Self::InvalidMoveDuration => "invalid_move_duration",
            Self::OutOfBounds => "out_of_bounds",
            Self::BlockedCell => "blocked_cell",
            Self::UnknownTransition => "unknown_transition",
            Self::WrongTransitionArea => "wrong_transition_area",
            Self::NotAtTransitionTrigger => "not_at_transition_trigger",
            Self::ActorNotAlive => "actor_not_alive",
            Self::ActorAsleep => "actor_asleep",
            Self::PostureLocked => "posture_locked",
            Self::MeleeWhileKneeling => "melee_while_kneeling",
            Self::MoveCooldown => "move_cooldown",
            Self::FireCooldown => "fire_cooldown",
            Self::NoWeaponEquipped => "no_weapon_equipped",
            Self::WeaponNotCertified => "weapon_not_certified",
            Self::OutOfRange => "out_of_range",
            Self::LosBlocked => "los_blocked",
            Self::QueueFull => "queue_full",
            Self::QueueEntryUnknown => "queue_entry_unknown",
            Self::InsufficientAction => "insufficient_action",
            Self::EconomyCooldown => "economy_cooldown",
            Self::SampleCooldown => "sample_cooldown",
            Self::UnknownItem => "unknown_item",
            Self::ItemUnavailable => "item_unavailable",
            Self::AmmoUnavailable => "ammo_unavailable",
            Self::NotAtStockpile => "not_at_stockpile",
            Self::UnknownEffect => "unknown_effect",
            Self::NoCloneFacility => "no_clone_facility",
            Self::UnknownCloneFacility => "unknown_clone_facility",
            Self::InvalidCloneRespawn => "invalid_clone_respawn",
            Self::NotAtBankTerminal => "not_at_bank_terminal",
            Self::InvalidBankQuantity => "invalid_bank_quantity",
            Self::BankStackMissing => "bank_stack_missing",
            Self::BankCapacity => "bank_capacity",
            Self::BankOverflow => "bank_overflow",
            Self::InvalidResourceFamily => "invalid_resource_family",
            Self::IngredientUnavailable => "ingredient_unavailable",
            Self::MissingSurveyTool => "missing_survey_tool",
            Self::ExtractorAlreadyPlaced => "extractor_already_placed",
            Self::NoPlacedExtractor => "no_placed_extractor",
            Self::NotExtractorOwner => "not_extractor_owner",
            Self::NotAtExtractor => "not_at_extractor",
            Self::CampAlreadyPlaced => "camp_already_placed",
            Self::NoPlacedCamp => "no_placed_camp",
            Self::NotCampOwner => "not_camp_owner",
            Self::NotAtCamp => "not_at_camp",
            Self::ExtractorHopperEmpty => "extractor_hopper_empty",
            Self::ExtractorHopperFull => "extractor_hopper_full",
            Self::ExtractorBatteryPresent => "extractor_battery_present",
            Self::MissingBattery => "missing_battery",
            Self::ExtractorBusy => "extractor_busy",
            Self::UnknownSchematic => "unknown_schematic",
            Self::InvalidExperimentation => "invalid_experimentation",
            Self::TargetUnavailable => "target_unavailable",
            Self::TargetProtected => "target_protected",
            Self::TargetNotHarvestable => "target_not_harvestable",
            Self::ContainerFull => "container_full",
            Self::LootOutOfRange => "loot_out_of_range",
            Self::LootNoRights => "loot_no_rights",
            Self::LootNotLootable => "loot_not_lootable",
            Self::LootMissingStack => "loot_missing_stack",
            Self::LootInvalidQuantity => "loot_invalid_quantity",
            Self::LootTargetUnknown => "loot_target_unknown",
            Self::UnknownSkillBox => "unknown_skill_box",
            Self::SkillAlreadyLearned => "skill_already_learned",
            Self::SkillNotLearned => "skill_not_learned",
            Self::SkillRequiredByLearnedBox => "skill_required_by_learned_box",
            Self::SkillPrerequisiteMissing => "skill_prerequisite_missing",
            Self::InsufficientProfessionXp => "insufficient_profession_xp",
            Self::InsufficientCredits => "insufficient_credits",
            Self::InsufficientSkillPoints => "insufficient_skill_points",
            Self::TrainerUnavailable => "trainer_unavailable",
            Self::CraftSessionActive => "craft_session_active",
            Self::NoCraftSession => "no_craft_session",
            Self::TradeSessionActive => "trade_session_active",
            Self::NoTradeSession => "no_trade_session",
            Self::TradeNotLocked => "trade_not_locked",
            Self::CraftSlotUnfilled => "craft_slot_unfilled",
            Self::CraftSlotMismatch => "craft_slot_mismatch",
            Self::CraftAlreadyAssembled => "craft_already_assembled",
            Self::CraftNotAssembled => "craft_not_assembled",
            Self::InvalidExperimentLine => "invalid_experiment_line",
            Self::InvalidCraftName => "invalid_craft_name",
            Self::SchematicUsesExceeded => "schematic_uses_exceeded",
            Self::UnknownFactory => "unknown_factory",
            Self::NotAtFactory => "not_at_factory",
            Self::FactoryDraftMissing => "factory_draft_missing",
            Self::FactoryDraftMismatch => "factory_draft_mismatch",
            Self::ToolAlreadyHeld => "tool_already_held",
            Self::StarterToolCooldown => "starter_tool_cooldown",
            Self::UnknownProfessionTitle => "unknown_profession_title",
            Self::UnknownCareerGoal => "unknown_career_goal",
            Self::CannotGroupSelf => "cannot_group_self",
            Self::AlreadyInGroup => "already_in_group",
            Self::NotInGroup => "not_in_group",
            Self::NotGroupLeader => "not_group_leader",
            Self::NotGroupMember => "not_group_member",
            Self::GroupFull => "group_full",
            Self::NoPendingInvite => "no_pending_invite",
            Self::CannotDuelSelf => "cannot_duel_self",
            Self::AlreadyDueling => "already_dueling",
            Self::NoPendingDuelChallenge => "no_pending_duel_challenge",
            Self::NotAtPaTerminal => "not_at_pa_terminal",
            Self::GuildNameTooLong => "guild_name_too_long",
            Self::GuildTagTooLong => "guild_tag_too_long",
            Self::GuildNameExists => "guild_name_exists",
            Self::GuildTagExists => "guild_tag_exists",
            Self::AlreadyInGuild => "already_in_guild",
            Self::NotInGuild => "not_in_guild",
            Self::NoGuildPermission => "no_guild_permission",
            Self::GuildNotFound => "guild_not_found",
            Self::InviteExpired => "invite_expired",
            Self::InviteAlreadyPending => "invite_already_pending",
            Self::InviteNotFound => "invite_not_found",
            Self::AlreadyWaring => "already_waring",
            Self::NotWaring => "not_waring",
            Self::NotInDuel => "not_in_duel",
            Self::UnknownCropSpecies => "unknown_crop_species",
            Self::MissingGeneSampler => "missing_gene_sampler",
            Self::MissingGenomeScanner => "missing_genome_scanner",
            Self::MissingSpliceBench => "missing_splice_bench",
            Self::GenomeUnavailable => "genome_unavailable",
            Self::SpliceSessionActive => "splice_session_active",
            Self::NoSpliceSession => "no_splice_session",
            Self::SpliceSlotMismatch => "splice_slot_mismatch",
            Self::SpliceAlreadyAssembled => "splice_already_assembled",
            Self::SpliceNotAssembled => "splice_not_assembled",
            Self::InvalidSpliceLocus => "invalid_splice_locus",
            Self::InvalidSpliceExperiment => "invalid_splice_experiment",
            Self::ParcelLimitReached => "parcel_limit_reached",
            Self::NotInHousingRegion => "not_in_housing_region",
            Self::ParcelOverlap => "parcel_overlap",
            Self::TooCloseToPoi => "too_close_to_poi",
            Self::TooCloseToRoad => "too_close_to_road",
            Self::NoClaimZone => "no_claim_zone",
            Self::UnknownParcel => "unknown_parcel",
            Self::NotParcelOwner => "not_parcel_owner",
            Self::UpkeepNotDue => "upkeep_not_due",
            Self::OutsideFarmYard => "outside_farm_yard",
            Self::TileNotTilled => "tile_not_tilled",
            Self::TileAlreadyTilled => "tile_already_tilled",
            Self::TileOccupied => "tile_occupied",
            Self::SeedNotOwned => "seed_not_owned",
            Self::StructureFootprintBlocked => "structure_footprint_blocked",
            Self::NoFarmStructure => "no_farm_structure",
            Self::BuildCatalogUnknown => "build_catalog_unknown",
            Self::BuildOverlap => "build_overlap",
            Self::BuildNotOwner => "build_not_owner",
            Self::TileEmpty => "tile_empty",
            Self::TileAlreadyFertilized => "tile_already_fertilized",
            Self::CropNotMature => "crop_not_mature",
        }
    }
}
