import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const read = (name) => readFile(path.join(root, name), "utf8");
describe("standalone site deploy contracts", () => {
  it("keeps the site private, immutable, and separately fronted", async () => { const tf = await read("ops/deploy/terraform/modules/successor-shard/site.tf"); const publish = await read("ops/deploy/scripts/publish-site.mjs"); assert.match(tf, /aws_s3_bucket.*site/); assert.match(tf, /aws_cloudfront_origin_access_control.*site/); assert.match(publish, /site\/releases/); assert.match(tf, /aws_s3_bucket_policy.*site/); assert.match(tf, /AWS:SourceArn/); assert.match(tf, /site_rewrite/); assert.match(tf, /site\/current/); });
  it("does not forward account credentials into game or chat", async () => {
    const tf = await read("ops/deploy/terraform/modules/successor-shard/site.tf");
    const api = tf.match(/resource "aws_cloudfront_origin_request_policy" "site_api"[\s\S]*?\n}\n/)[0];
    const game = tf.match(/resource "aws_cloudfront_origin_request_policy" "site_game"[\s\S]*?\n}\n/)[0];
    const chat = tf.match(/resource "aws_cloudfront_origin_request_policy" "site_chat"[\s\S]*?\n}\n/)[0];
    assert.match(api, /__Host-successor_session/);
    assert.match(api, /X-CSRF-Token/);
    assert.match(game, /cookie_behavior = "none"/);
    assert.match(chat, /cookie_behavior = "none"/);
    assert.doesNotMatch(game, /Authorization/);
    assert.doesNotMatch(chat, /Authorization/);
    assert.match(game, /Sec-WebSocket-Key/);
    assert.match(chat, /Sec-WebSocket-Protocol/);
    assert.match(tf, /Managed-CachingDisabled/);
  });
  it("forwards browser and native API credentials with a zero default TTL", async () => {
    const tf = await read("ops/deploy/terraform/modules/successor-shard/site.tf");
    const originPolicy = tf.match(/resource "aws_cloudfront_origin_request_policy" "site_api"[\s\S]*?\n}\n/)[0];
    assert.match(originPolicy, /header_behavior = "whitelist"/);
    assert.doesNotMatch(originPolicy, /Authorization|header_behavior = "(?:allViewer|allExcept)"/);
    assert.match(originPolicy, /headers \{ items = \["Accept", "Content-Type", "Origin", "X-CSRF-Token", "Sec-Fetch-Site", "Sec-Fetch-Mode", "Sec-Fetch-Dest"\] \}/);
    assert.match(originPolicy, /cookies \{ items = \["__Host-successor_session"\] \}/);
    assert.match(originPolicy, /query_string_behavior = "all"/);
    const cachePolicy = tf.match(/resource "aws_cloudfront_cache_policy" "site_api"[\s\S]*?\n}\n/)[0];
    assert.match(cachePolicy, /default_ttl = 0/);
    assert.match(cachePolicy, /max_ttl\s+= 1/);
    assert.match(cachePolicy, /min_ttl\s+= 0/);
    assert.match(cachePolicy, /header_behavior = "whitelist"/);
    assert.match(cachePolicy, /headers \{ items = \["Authorization"\] \}/);
    assert.match(cachePolicy, /cookie_behavior = "none"/);
    assert.match(cachePolicy, /query_string_behavior = "none"/);
    const alpha = tf.match(/ordered_cache_behavior \{[\s\S]*?path_pattern\s+= "\/alpha-api\/\*"[\s\S]*?\n\s+\}/)[0];
    assert.match(alpha, /target_origin_id\s+= "successor-alb"/);
    assert.match(alpha, /allowed_methods\s+= \["GET", "HEAD", "OPTIONS", "PUT", "PATCH", "POST", "DELETE"\]/);
    assert.match(alpha, /cache_policy_id\s+= aws_cloudfront_cache_policy\.site_api\.id/);
    assert.match(alpha, /origin_request_policy_id\s+= aws_cloudfront_origin_request_policy\.site_api\.id/);
    assert.match(alpha, /response_headers_policy_id\s+= aws_cloudfront_response_headers_policy\.site_dynamic\.id/);
    const dynamic = tf.match(/resource "aws_cloudfront_response_headers_policy" "site_dynamic"[\s\S]*?\n}\n/)[0];
    assert.match(dynamic, /header\s+= "Cache-Control"[\s\S]*value\s+= "no-store, no-cache, must-revalidate"/);
  });
  it("uses the certificate-matching public game hostname for the HTTPS origin", async () => { const tf = await read("ops/deploy/terraform/modules/successor-shard/site.tf"); const origin = tf.match(/origin \{\n\s+domain_name = var\.dns_name[\s\S]*?origin_id\s+= "successor-alb"[\s\S]*?origin_protocol_policy = "https-only"[\s\S]*?\n\s+\}/); assert.ok(origin, "site API origin must use the world hostname covered by the ACM certificate"); assert.doesNotMatch(tf, /domain_name = aws_lb\.this\.dns_name/); });
  it("uses strict site CSP, valid dynamic methods, WAF path limits, and public game ingress", async () => { const tf = await read("ops/deploy/terraform/modules/successor-shard/site.tf"); const waf = await read("ops/deploy/terraform/modules/successor-shard/waf.tf"); const main = await read("ops/deploy/terraform/modules/successor-shard/main.tf"); assert.match(tf, /content_security_policy =/); assert.match(tf, /frame-ancestors 'none'/); assert.match(tf, /strict-origin-when-cross-origin/); assert.match(tf, /web_acl_id\s*=\s*aws_wafv2_web_acl\.site\.arn/); for (const path of ["register", "login", "device/start", "device/poll"]) assert.match(waf, new RegExp(`/alpha-api/${path}`)); assert.match(waf, /AWSManagedRulesCommonRuleSet/); assert.match(waf, /AWSManagedRulesKnownBadInputsRuleSet/); assert.match(tf, /allowed_methods\s*=\s*\["GET", "HEAD", "OPTIONS", "PUT", "PATCH", "POST", "DELETE"\]/); assert.doesNotMatch(tf, /cached_methods\s*=\s*\[\]/); assert.doesNotMatch(main, /aws_ec2_managed_prefix_list\.cloudfront_origin_facing/); assert.match(main, /description = "Public TLS for game, chat, and storefront origin"[\s\S]*cidr_blocks = \["0\.0\.0\.0\/0"\]/); assert.match(main, /Explicit staging readiness access/); });
  it("contains no runtime secret values or Route 53 site writes", async () => { const tf = await read("ops/deploy/terraform/modules/successor-shard/site.tf"); assert.doesNotMatch(tf, /runtime-secret.*value/); assert.doesNotMatch(tf, /aws_route53_record/); assert.match(tf, /aws_acm_certificate.*site/); assert.match(tf, /site_acm_dns_validation_records|site_acm_dns/); });

  it("serves public /current.json from site/current.json with no-store headers", async () => {
    const tf = await read("ops/deploy/terraform/modules/successor-shard/site.tf");
    const publish = await read("ops/deploy/scripts/publish-site.mjs");
    const promote = await read("ops/deploy/scripts/promote-site.mjs");
    assert.match(tf, /path_pattern\s+= "\/current\.json"/);
    assert.match(tf, /if \(uri === '\/current\.json'\) \{[\s\S]*request\.uri = '\/site\/current\.json'/);
    const pointerBehavior = tf.match(/ordered_cache_behavior \{[\s\S]*?path_pattern\s+= "\/current\.json"[\s\S]*?\n\s+\}/)[0];
    assert.match(pointerBehavior, /target_origin_id\s+= "site-s3"/);
    assert.match(pointerBehavior, /function_arn = aws_cloudfront_function\.site_rewrite\.arn/);
    assert.match(pointerBehavior, /cache_policy_id\s+= data\.aws_cloudfront_cache_policy\.site_dynamic\.id/);
    assert.match(pointerBehavior, /response_headers_policy_id\s+= aws_cloudfront_response_headers_policy\.site_dynamic\.id/);
    assert.match(publish, /PUBLIC_SITE_POINTER_CONTENT_TYPE = "application\/json"/);
    assert.match(publish, /PUBLIC_SITE_POINTER_CACHE_CONTROL = "no-store, no-cache, must-revalidate"/);
    assert.match(publish, /object_key: PUBLIC_SITE_POINTER_OBJECT_KEY/);
    assert.match(promote, /pointer_destination: `\$\{bucket\}\/\$\{route\.object_key\}`/);
    assert.match(promote, /assertPublicSitePointerBody/);
  });
});
