"""Three from-zero Dustgate direction studies, rendered at equal framing.

Run one direction per Blender process so scene state cannot leak:

    blender -b -P directions.py -- a
    blender -b -P directions.py -- b
    blender -b -P directions.py -- c

Each study is built only from primitives generated by `dgkit`. No existing
Dustgate geometry, builder script, texture, or render is opened or referenced.
Output goes to the ignored proof root; nothing here touches runtime assets.

Study axes that must differ, not just palette:
  A "Leeward Terrace" - linear settlement in the lee of one ancient wall,
      monopitch roofs on a shared eave datum, single long interior bays.
  B "Dust Well"       - radial settlement around a shallow sink, half-buried
      cast drums with conical caps, hearth-centred radial interiors.
  C "Frame Ward"      - dispersed tall shed frames on plinths, barrel vault and
      gable roofs, two-level workshop interiors.
"""

from __future__ import annotations

import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bpy  # type: ignore

import dgkit as dg
from dgpaths import proof

# --------------------------------------------------------------------------
# shared framing: identical for all three studies
# --------------------------------------------------------------------------

STUDY_TARGET = (0.0, 2.0, 1.6)
STUDY_WIDE_FRUSTUM = 34.0
STUDY_PLAN_FRUSTUM = 44.0
STUDY_GAMEPLAY_FRUSTUM = 12.5  # 100% zoom
PROXY_HEIGHT = 1.75
PROXY_RADIUS = 0.3  # matches the 300 milli-cell authority movement circle


def scale_proxies(spots, material) -> list:
    return [
        dg.capsule(f"proxy__{i:02d}", x, y, 0.0, PROXY_RADIUS, PROXY_HEIGHT, material)
        for i, (x, y) in enumerate(spots)
    ]


def annulus(name, cx, cy, z, r_in, r_out, segments, material):
    """Flat ring, used where a pit must not be covered by the ground plane."""
    inner = dg.circle_poly(cx, cy, r_in, segments)
    outer = dg.circle_poly(cx, cy, r_out, segments)
    verts = [(x, y, z) for x, y in inner] + [(x, y, z) for x, y in outer]
    faces = []
    for i in range(segments):
        j = (i + 1) % segments
        faces.append((i, j, segments + j, segments + i))
    return dg.mesh_from(name, verts, faces, material, recalc=False)


# --------------------------------------------------------------------------
# direction A: Leeward Terrace
# --------------------------------------------------------------------------


def build_a() -> dict:
    dg.reset()
    sand = dg.mat("A_sand", "#b9a07c", rough=0.96)
    anc = dg.mat("A_ancient", "#5c5b58", rough=0.9)
    anc_dk = dg.mat("A_ancient_deep", "#403f3d", rough=0.92)
    panel = dg.mat("A_panel", "#8d8377", rough=0.82)
    panel_dk = dg.mat("A_panel_shade", "#6b6257", rough=0.85)
    roof = dg.mat("A_roof", "#cdc2a6", rough=0.74)
    reveal = dg.mat("A_reveal", "#2b2724", rough=0.95)
    oxide = dg.mat("A_oxide", "#8c4a2a", rough=0.8)
    steel = dg.mat("A_steel", "#57534d", rough=0.55, metal=0.7)
    amber = dg.mat("A_amber", "#ffb347", rough=0.4, emission="#ffb347", emission_strength=3.0)

    dg.ground_plane("ground", 140.0, sand)

    # --- ancient windbreak wall, broken into three unequal segments ---
    dg.boxm("ancient_seg_west", -20.0, -5.2, 8.0, 10.6, 0.0, 7.4, anc, chamfer=0.25,
            top_inset=0.5, base_flare=0.4)
    dg.boxm("ancient_seg_mid", -2.2, 9.4, 8.0, 10.6, 0.0, 6.6, anc, chamfer=0.25,
            top_inset=0.45, base_flare=0.4)
    dg.boxm("ancient_seg_stub", 9.4, 17.5, 8.2, 10.4, 0.0, 3.5, anc, chamfer=0.3,
            top_inset=0.6, base_flare=0.35)
    for i, x in enumerate((-18.2, -14.4, -10.6, -6.8, 0.4, 4.2, 7.8)):
        dg.boxm(f"ancient_bay_{i:02d}", x - 0.55, x + 0.55, 7.35, 8.05, 0.0, 5.6,
                anc_dk, top_inset=0.12)
    for i, (x, y, r) in enumerate(((-4.2, 7.2, 1.1), (-3.1, 6.2, 0.7), (10.4, 7.4, 0.9))):
        dg.boxm(f"ancient_rubble_{i:02d}", x - r, x + r, y - r, y + r, 0.0, r * 1.1,
                anc, chamfer=r * 0.4, corner_segments=2)

    # --- cloning: pod bulges + overhead hoist + clerestory monitor ---
    cx0, cx1, cy0, cy1 = -17.0, -7.0, -0.4, 7.6
    t = 0.35
    dg.boxm("clone_wall_back", cx0, cx1, cy1 - t, cy1, 0.0, 4.5, panel)
    dg.prism("clone_wall_west", [(cy0, 0.0), (cy1, 0.0), (cy1, 4.5), (cy0, 3.4)], "x",
             cx0, cx0 + t, panel)
    dg.prism("clone_wall_east", [(cy0, 0.0), (cy1, 0.0), (cy1, 4.5), (cy0, 3.4)], "x",
             cx1 - t, cx1, panel)
    dg.boxm("clone_wall_front_w", cx0, -12.9, cy0, cy0 + t, 0.0, 3.4, panel)
    dg.boxm("clone_wall_front_e", -11.1, cx1, cy0, cy0 + t, 0.0, 3.4, panel)
    dg.boxm("clone_lintel", -12.9, -11.1, cy0, cy0 + t, 2.4, 3.4, panel_dk)
    dg.boxm("clone_floor", cx0, cx1, cy0, cy1, -0.05, 0.02, panel_dk)
    dg.boxm("clone_interior_dark", cx0 + t, cx1 - t, cy0 + t, cy1 - t, 0.02, 0.06, reveal)
    dg.slab_sloped("clone_roof", cx0 - 0.35, cx1 + 0.35, cy0 - 1.15, cy1 + 0.35, 3.5, 4.6,
                   0.22, roof)
    dg.boxm("clone_clerestory", cx0 + 0.6, cx1 - 0.6, 4.6, 6.4, 4.45, 5.5, panel)
    dg.boxm("clone_clerestory_glass", cx0 + 0.8, cx1 - 0.8, 4.5, 4.62, 4.7, 5.25, reveal)
    dg.slab_sloped("clone_clerestory_roof", cx0 + 0.4, cx1 - 0.4, 4.4, 6.55, 5.35, 5.62,
                   0.16, roof)
    for i, y in enumerate((1.1, 3.4, 5.7)):
        dg.cylinder(f"clone_pod_{i:02d}", cx0 + 0.1, y, 0.0, 2.55, 0.95, panel, segments=18)
        dg.cylinder(f"clone_pod_cap_{i:02d}", cx0 + 0.1, y, 2.55, 3.15, 0.95, oxide,
                    segments=18, top_radius=0.42)
        dg.boxm(f"clone_pod_glass_{i:02d}", cx0 - 1.0, cx0 - 0.72, y - 0.5, y + 0.5, 0.7, 2.1,
                reveal, chamfer=0.12, corner_segments=2)
    dg.boxm("clone_hoist_rail", cx0 - 0.6, cx1 + 0.6, -1.55, -1.15, 3.85, 4.25, steel)
    for i, x in enumerate((cx0 - 0.4, cx1 + 0.4)):
        dg.cylinder(f"clone_hoist_post_{i:02d}", x, -1.35, 0.0, 3.9, 0.16, steel, segments=10)
    dg.boxm("clone_signal", -12.4, -11.6, cy0 - 0.05, cy0 + 0.06, 3.5, 3.72, amber)

    # --- commerce: deep shaded veranda + heavy vault block ---
    mx0, mx1, my0, my1 = -5.4, 6.6, -1.4, 7.6
    dg.boxm("mkt_wall_back", mx0, mx1, my1 - t, my1, 0.0, 4.5, panel)
    dg.prism("mkt_wall_west", [(my0, 0.0), (my1, 0.0), (my1, 4.5), (my0, 3.45)], "x",
             mx0, mx0 + t, panel)
    dg.prism("mkt_wall_east", [(my0, 0.0), (my1, 0.0), (my1, 4.5), (my0, 3.45)], "x",
             mx1 - t, mx1, panel)
    dg.boxm("mkt_floor", mx0, mx1, my0, my1, -0.05, 0.02, panel_dk)
    dg.boxm("mkt_interior_dark", mx0 + t, mx1 - t, my0 + t, my1 - t, 0.02, 0.06, reveal)
    # shutter bank behind a counter shelf, front wall pulled north of the eave
    dg.boxm("mkt_front_wall_w", mx0, -3.0, 0.2, 0.55, 0.0, 3.45, panel)
    dg.boxm("mkt_front_wall_e", 3.4, mx1, 0.2, 0.55, 0.0, 3.45, panel)
    dg.boxm("mkt_front_lintel", -3.0, 3.4, 0.2, 0.55, 2.5, 3.45, panel_dk)
    dg.boxm("mkt_counter", -3.0, 3.4, 0.2, 0.9, 0.0, 1.05, panel_dk, chamfer=0.1)
    for i, x in enumerate((-2.2, 0.2, 2.6)):
        dg.boxm(f"mkt_shutter_{i:02d}", x - 1.0, x + 1.0, 0.1, 0.22, 1.05, 2.5, reveal)
    dg.slab_sloped("mkt_roof", mx0 - 0.4, mx1 + 0.4, my0 - 1.85, my1 + 0.35, 3.4, 4.6,
                   0.24, roof)
    for i, x in enumerate((-4.6, -1.5, 1.7, 4.8)):
        dg.cylinder(f"mkt_post_{i:02d}", x, my0 - 1.35, 0.0, 3.45, 0.15, steel, segments=10)
    dg.boxm("mkt_vault", 4.9, 8.5, 2.9, 7.6, 0.0, 4.25, panel_dk, chamfer=0.4,
            corner_segments=2, base_flare=0.28, top_inset=0.1)
    dg.boxm("mkt_vault_band", 4.85, 8.55, 2.85, 7.65, 2.45, 2.95, steel)
    dg.boxm("mkt_vault_hatch", 4.75, 4.92, 4.4, 6.1, 0.1, 2.3, steel)
    dg.boxm("mkt_signal", -0.4, 0.4, 0.05, 0.16, 2.55, 2.75, amber)

    # --- shelter: storm porch + water catch ---
    sx0, sx1, sy0, sy1 = 8.8, 14.8, 1.8, 7.6
    dg.boxm("hab_wall_back", sx0, sx1, sy1 - t, sy1, 0.0, 3.6, panel)
    dg.prism("hab_wall_west", [(sy0, 0.0), (sy1, 0.0), (sy1, 3.6), (sy0, 2.9)], "x",
             sx0, sx0 + t, panel)
    dg.prism("hab_wall_east", [(sy0, 0.0), (sy1, 0.0), (sy1, 3.6), (sy0, 2.9)], "x",
             sx1 - t, sx1, panel)
    dg.boxm("hab_wall_front_w", sx0, 10.9, sy0, sy0 + t, 0.0, 2.9, panel)
    dg.boxm("hab_wall_front_e", 12.7, sx1, sy0, sy0 + t, 0.0, 2.9, panel)
    dg.boxm("hab_lintel", 10.9, 12.7, sy0, sy0 + t, 2.2, 2.9, panel_dk)
    dg.boxm("hab_floor", sx0, sx1, sy0, sy1, -0.05, 0.02, panel_dk)
    dg.boxm("hab_interior_dark", sx0 + t, sx1 - t, sy0 + t, sy1 - t, 0.02, 0.06, reveal)
    dg.slab_sloped("hab_roof", sx0 - 0.3, sx1 + 0.3, sy0 - 0.35, sy1 + 0.3, 2.95, 3.7,
                   0.2, roof)
    dg.slab_sloped("hab_porch", 10.4, 13.2, 0.1, 1.85, 2.15, 2.62, 0.1, oxide)
    for i, x in enumerate((10.55, 13.05)):
        dg.cylinder(f"hab_porch_post_{i:02d}", x, 0.3, 0.0, 2.2, 0.1, steel, segments=8)
    dg.cylinder("hab_cistern", 15.7, 4.6, 0.0, 2.45, 1.2, panel_dk, segments=20)
    dg.cylinder("hab_cistern_cap", 15.7, 4.6, 2.45, 2.95, 1.2, oxide, segments=20,
                top_radius=0.5)

    # --- travel terminal: isolated footprint only, no connective surface ---
    dg.boxm("travel_pad", 0.9, 2.9, -6.7, -5.1, 0.0, 0.3, panel_dk, chamfer=0.2,
            corner_segments=2)
    dg.boxm("travel_console", 1.3, 2.5, -6.2, -5.7, 0.3, 1.35, panel)
    dg.boxm("travel_screen", 1.4, 2.4, -6.24, -6.16, 0.75, 1.3, amber)
    dg.cylinder("travel_mast", 1.9, -5.4, 0.3, 5.4, 0.14, steel, segments=10)
    dg.boxm("travel_vane", 1.1, 2.7, -5.5, -5.32, 4.6, 5.1, oxide)

    proxies = scale_proxies(
        ((-12.0, -1.9), (0.0, -2.6), (11.8, 0.7), (1.9, -4.4), (-6.6, 2.2)),
        dg.mat("A_proxy", "#d7d9d4", rough=0.6),
    )
    return {"name": "a", "label": "Leeward Terrace", "proxies": proxies,
            "gameplay_target": (-0.2, 0.6, 1.2)}


# --------------------------------------------------------------------------
# direction B: Dust Well
# --------------------------------------------------------------------------


def build_b() -> dict:
    dg.reset()
    sand = dg.mat("B_sand", "#b5a382", rough=0.96)
    cast = dg.mat("B_cast", "#b2a996", rough=0.88)
    cast_dk = dg.mat("B_cast_shade", "#8d8471", rough=0.9)
    mono = dg.mat("B_monolith", "#6e6a60", rough=0.9)
    oxide = dg.mat("B_oxide_cap", "#7b3b2c", rough=0.78)
    dark = dg.mat("B_aperture", "#241f1c", rough=0.95)
    steel = dg.mat("B_steel", "#4f4c47", rough=0.5, metal=0.7)
    phos = dg.mat("B_phosphor", "#7fd6a3", rough=0.4, emission="#7fd6a3",
                  emission_strength=2.6)

    SINK_Z = -1.15
    SINK_R = 9.4
    RIM_R = 11.0
    annulus("ground_ring", 0.0, 0.0, 0.0, RIM_R, 70.0, 48, sand)
    dg.cylinder("sink_wall", 0.0, 0.0, SINK_Z, 0.0, SINK_R, cast_dk, segments=48,
                top_radius=RIM_R)
    dg.cylinder("sink_floor", 0.0, 0.0, SINK_Z - 0.08, SINK_Z, SINK_R, sand, segments=48)
    for i in range(8):
        a = 2 * math.pi * i / 8 + 0.19
        dg.boxm(f"sink_step_{i:02d}", -0.9, 0.9, -0.7, 0.7, SINK_Z, SINK_Z + 0.35, cast_dk,
                chamfer=0.3, corner_segments=2)
        step = bpy.context.scene.objects[f"sink_step_{i:02d}"]
        step.location = (math.cos(a) * (SINK_R - 1.4), math.sin(a) * (SINK_R - 1.4), 0.0)

    def drum(prefix, cx, cy, radius, z0, wall_top, cap_top, cap_radius, door_angle,
             segments=28):
        dg.cylinder(f"{prefix}_shell", cx, cy, z0, wall_top, radius, cast, segments=segments)
        dg.cylinder(f"{prefix}_shell_band", cx, cy, wall_top - 0.42, wall_top + 0.06,
                    radius + 0.14, cast_dk, segments=segments)
        dg.cylinder(f"{prefix}_cap", cx, cy, wall_top + 0.06, cap_top, radius + 0.02, oxide,
                    segments=segments, top_radius=cap_radius)
        dg.cylinder(f"{prefix}_floor", cx, cy, z0 - 0.05, z0 + 0.02, radius - 0.3, cast_dk,
                    segments=segments)
        dg.cylinder(f"{prefix}_interior", cx, cy, z0 + 0.02, z0 + 0.06, radius - 0.42, dark,
                    segments=segments)
        # threshold reveal: a dark recess block set into the shell, footprint-only
        dx, dy = math.cos(door_angle), math.sin(door_angle)
        door = dg.boxm(f"{prefix}_door_reveal", -1.0, 1.0, -0.45, 0.45, z0, z0 + 2.25, dark)
        door.location = (cx + dx * (radius - 0.1), cy + dy * (radius - 0.1), 0.0)
        door.rotation_euler = (0.0, 0.0, door_angle - math.pi * 0.5)
        jamb = dg.boxm(f"{prefix}_door_jamb", -1.25, 1.25, -0.2, 0.2, z0, z0 + 2.55, cast_dk)
        jamb.location = (cx + dx * (radius + 0.16), cy + dy * (radius + 0.16), 0.0)
        jamb.rotation_euler = (0.0, 0.0, door_angle - math.pi * 0.5)

    # cloning drum: tall lantern + vent stack
    drum("clone", -9.6, 5.0, 5.4, SINK_Z, 3.2, 5.0, 1.5, -math.pi * 0.62)
    dg.cylinder("clone_lantern", -9.6, 5.0, 5.0, 6.0, 1.5, cast, segments=20)
    dg.cylinder("clone_lantern_cap", -9.6, 5.0, 6.0, 6.5, 1.6, oxide, segments=20,
                top_radius=0.6)
    dg.boxm("clone_lantern_glass", -10.9, -8.3, 3.86, 3.98, 5.15, 5.85, phos)
    dg.cylinder("clone_vent", -14.2, 7.4, SINK_Z, 7.6, 0.55, steel, segments=14)
    dg.cylinder("clone_vent_hood", -14.2, 7.4, 7.6, 8.3, 0.75, oxide, segments=14,
                top_radius=0.3)
    for i, a in enumerate((-2.2, -1.55, -0.9)):
        px, py = -9.6 + math.cos(a) * 5.9, 5.0 + math.sin(a) * 5.9
        dg.cylinder(f"clone_pod_{i:02d}", px, py, SINK_Z, SINK_Z + 2.4, 1.05, cast_dk,
                    segments=16)
        dg.cylinder(f"clone_pod_cap_{i:02d}", px, py, SINK_Z + 2.4, SINK_Z + 3.0, 1.05,
                    oxide, segments=16, top_radius=0.45)

    # commerce drum: broad shade brim over its whole footprint
    drum("mkt", 7.4, 3.4, 6.2, SINK_Z, 2.9, 4.5, 2.1, -math.pi * 0.78, segments=32)
    dg.cylinder("mkt_brim", 7.4, 3.4, 2.96, 3.3, 8.1, cast_dk, segments=32, top_radius=7.7)
    for i in range(6):
        a = 2 * math.pi * i / 6 + 0.3
        dg.cylinder(f"mkt_brim_post_{i:02d}", 7.4 + math.cos(a) * 7.5,
                    3.4 + math.sin(a) * 7.5, SINK_Z, 2.98, 0.14, steel, segments=8)
    dg.cylinder("mkt_vault", 13.6, 8.0, 0.0, 3.5, 2.6, mono, segments=20, top_radius=2.35)
    dg.cylinder("mkt_vault_cap", 13.6, 8.0, 3.5, 3.9, 2.45, steel, segments=20,
                top_radius=1.9)
    dg.boxm("mkt_vault_hatch", 11.2, 11.42, 7.1, 8.9, 0.0, 2.2, steel)

    # shelter drum: small, on the rim, outside the sink
    drum("hab", 1.2, -12.0, 3.6, 0.0, 2.4, 3.5, 1.1, math.pi * 0.5, segments=22)
    dg.cylinder("hab_cistern", 5.3, -13.6, 0.0, 2.0, 1.05, cast_dk, segments=16)
    dg.cylinder("hab_cistern_cap", 5.3, -13.6, 2.0, 2.4, 1.05, oxide, segments=16,
                top_radius=0.45)

    # --- ancient ribs: three colossal buried arc segments around the rim ---
    for i, (cx, cy, yaw, radius, flat, height_base) in enumerate((
        (-3.0, 21.0, 6.0, 8.6, 1.42, -2.6),
        (-21.5, 6.5, 68.0, 7.4, 1.30, -2.2),
        (19.5, 14.0, -42.0, 6.6, 1.18, -2.0),
    )):
        profile = dg.arc_profile(radius, 11, height_base, 0.0, 0.0, flat)
        rib = dg.prism(f"ancient_rib_{i:02d}", profile, "y", -1.5, 1.5, mono)
        rib.location = (cx, cy, 0.0)
        rib.rotation_euler = (0.0, 0.0, math.radians(yaw))
        core = dg.arc_profile(radius - 2.0, 11, height_base, 0.0, 0.0, flat * 0.94)
        inner = dg.prism(f"ancient_rib_core_{i:02d}", core, "y", -1.56, -1.42, cast_dk)
        inner.location = (cx, cy, 0.0)
        inner.rotation_euler = (0.0, 0.0, math.radians(yaw))

    dg.boxm("travel_pad", -1.1, 0.9, -6.2, -4.6, SINK_Z, SINK_Z + 0.28, cast_dk,
            chamfer=0.2, corner_segments=2)
    dg.cylinder("travel_column", -0.1, -5.4, SINK_Z + 0.28, 4.4, 0.42, cast, segments=16)
    dg.cylinder("travel_head", -0.1, -5.4, 4.4, 5.0, 0.62, oxide, segments=16,
                top_radius=0.28)
    dg.boxm("travel_screen", -0.6, 0.4, -5.86, -5.76, 1.0, 1.7, phos)

    proxies = scale_proxies(
        ((-5.0, 1.2), (1.6, -1.4), (1.2, -8.2), (-0.1, -4.2), (7.0, -2.6)),
        dg.mat("B_proxy", "#d7d9d4", rough=0.6),
    )
    return {"name": "b", "label": "Dust Well", "proxies": proxies,
            "gameplay_target": (1.0, 0.4, 0.6)}


# --------------------------------------------------------------------------
# direction C: Frame Ward
# --------------------------------------------------------------------------


def build_c() -> dict:
    dg.reset()
    sand = dg.mat("C_sand", "#bda887", rough=0.96)
    frame = dg.mat("C_frame", "#463830", rough=0.62, metal=0.35)
    canvas = dg.mat("C_canvas", "#d8d2c0", rough=0.9)
    zinc = dg.mat("C_zinc", "#9aa0a0", rough=0.55, metal=0.5)
    plinth = dg.mat("C_plinth", "#7d7468", rough=0.92)
    dark = dg.mat("C_shade", "#211d1a", rough=0.95)
    oxide = dg.mat("C_oxide", "#96502c", rough=0.78)
    mono = dg.mat("C_monolith", "#605d58", rough=0.9)
    amber = dg.mat("C_amber", "#ffc663", rough=0.4, emission="#ffc663",
                   emission_strength=3.0)

    dg.ground_plane("ground", 140.0, sand)

    def plinth_block(name, x0, x1, y0, y1, top):
        dg.boxm(name, x0, x1, y0, y1, -0.1, top, plinth, chamfer=0.22, corner_segments=2,
                base_flare=0.18)

    # --- cloning shed: exposed A-frame, barrel vault, tall vent mast ---
    ax0, ax1, ay0, ay1 = -15.0, -6.0, 0.5, 8.5
    plinth_block("clone_plinth", ax0 - 0.4, ax1 + 0.4, ay0 - 0.4, ay1 + 0.4, 0.6)
    dg.boxm("clone_floor", ax0, ax1, ay0, ay1, 0.55, 0.62, plinth)
    dg.boxm("clone_interior_dark", ax0 + 0.3, ax1 - 0.3, ay0 + 0.3, ay1 - 0.3, 0.62, 0.66,
            dark)
    dg.boxm("clone_wall_back", ax0, ax1, ay1 - 0.28, ay1, 0.6, 4.0, zinc)
    dg.boxm("clone_wall_west", ax0, ax0 + 0.28, ay0, ay1, 0.6, 4.0, zinc)
    dg.boxm("clone_wall_east", ax1 - 0.28, ax1, ay0, ay1, 0.6, 4.0, zinc)
    dg.boxm("clone_wall_front_w", ax0, -11.4, ay0, ay0 + 0.28, 0.6, 4.0, zinc)
    dg.boxm("clone_wall_front_e", -9.6, ax1, ay0, ay0 + 0.28, 0.6, 4.0, zinc)
    dg.boxm("clone_lintel", -11.4, -9.6, ay0, ay0 + 0.28, 2.9, 4.0, frame)
    vault = dg.arc_profile(4.35, 10, 3.9, (ay0 + ay1) * 0.5, 0.0, 0.60)
    dg.prism("clone_roof", vault, "x", ax0 - 0.45, ax1 + 0.45, canvas)
    for i, x in enumerate((ax0 - 0.2, -12.2, -10.5, -8.8, ax1 + 0.2)):
        rib = dg.arc_profile(4.5, 10, 3.85, (ay0 + ay1) * 0.5, 0.0, 0.60)
        dg.prism(f"clone_rib_{i:02d}", rib, "x", x - 0.11, x + 0.11, frame)
    for i, x in enumerate((-14.4, -11.9, -9.1, -6.6)):
        dg.boxm(f"clone_col_w_{i:02d}", x - 0.16, x + 0.16, ay0 - 0.3, ay0 + 0.02, 0.0, 4.05,
                frame)
        dg.boxm(f"clone_col_e_{i:02d}", x - 0.16, x + 0.16, ay1 - 0.02, ay1 + 0.3, 0.0, 4.05,
                frame)
    for i, y in enumerate((2.1, 4.5, 6.9)):
        dg.cylinder(f"clone_pod_{i:02d}", ax0 - 0.9, y, 0.0, 2.7, 0.9, zinc, segments=16)
        dg.cylinder(f"clone_pod_cap_{i:02d}", ax0 - 0.9, y, 2.7, 3.25, 0.9, oxide,
                    segments=16, top_radius=0.4)
        dg.boxm(f"clone_pod_glass_{i:02d}", ax0 - 1.85, ax0 - 1.6, y - 0.46, y + 0.46, 0.8,
                2.2, dark, chamfer=0.1, corner_segments=2)
    dg.cylinder("clone_mast", -16.4, 1.4, 0.0, 9.2, 0.17, frame, segments=10)
    for i, z in enumerate((6.4, 7.6, 8.6)):
        dg.boxm(f"clone_mast_arm_{i:02d}", -17.6, -15.2, 1.32, 1.48, z, z + 0.12, frame)
    dg.boxm("clone_signal", -10.9, -10.1, ay0 - 0.06, ay0 + 0.04, 3.0, 3.25, amber)

    # --- commerce shed: gable, open truss bay, mezzanine ---
    bx0, bx1, by0, by1 = -2.0, 9.0, -2.0, 7.0
    plinth_block("mkt_plinth", bx0 - 0.4, bx1 + 0.4, by0 - 0.4, by1 + 0.4, 0.55)
    dg.boxm("mkt_floor", bx0, bx1, by0, by1, 0.5, 0.57, plinth)
    dg.boxm("mkt_interior_dark", bx0 + 0.3, bx1 - 0.3, by0 + 0.3, by1 - 0.3, 0.57, 0.61,
            dark)
    dg.boxm("mkt_wall_back", bx0, bx1, by1 - 0.3, by1, 0.55, 4.3, zinc)
    apex_y = (by0 + by1) * 0.5
    dg.prism("mkt_wall_west", [(by0, 0.55), (by1, 0.55), (by1, 4.3), (apex_y, 6.5),
                               (by0, 4.3)], "x", bx0, bx0 + 0.3, zinc)
    dg.prism("mkt_wall_east", [(by0, 0.55), (by1, 0.55), (by1, 4.3), (apex_y, 6.5),
                               (by0, 4.3)], "x", bx1 - 0.3, bx1, zinc)
    dg.slab_sloped("mkt_roof_south", bx0 - 0.5, bx1 + 0.5, by0 - 0.9, apex_y, 4.15, 6.5,
                   0.22, canvas)
    dg.slab_sloped("mkt_roof_north", bx0 - 0.5, bx1 + 0.5, apex_y, by1 + 0.45, 6.5, 4.3,
                   0.22, canvas)
    dg.boxm("mkt_ridge", bx0 - 0.5, bx1 + 0.5, apex_y - 0.18, apex_y + 0.18, 6.42, 6.72,
            frame)
    for i, x in enumerate((bx0 + 0.15, 1.6, 5.4, bx1 - 0.15)):
        dg.prism(f"mkt_truss_s_{i:02d}", [(by0, 4.1), (apex_y, 6.42), (apex_y, 6.2),
                                          (by0, 3.88)], "x", x - 0.1, x + 0.1, frame)
        dg.prism(f"mkt_truss_n_{i:02d}", [(apex_y, 6.42), (by1, 4.25), (by1, 4.03),
                                          (apex_y, 6.2)], "x", x - 0.1, x + 0.1, frame)
        dg.boxm(f"mkt_tie_{i:02d}", x - 0.09, x + 0.09, by0, by1, 4.0, 4.16, frame)
    # open front bay: no south wall, only a counter and shutter frames
    dg.boxm("mkt_counter", 0.4, 6.6, by0 + 0.1, by0 + 0.85, 0.55, 1.6, plinth, chamfer=0.1)
    for i, x in enumerate((1.4, 3.5, 5.6)):
        dg.boxm(f"mkt_terminal_{i:02d}", x - 0.55, x + 0.55, 4.9, 5.7, 0.57, 1.85, frame,
                chamfer=0.1)
        dg.boxm(f"mkt_terminal_face_{i:02d}", x - 0.42, x + 0.42, 4.82, 4.92, 1.05, 1.7,
                amber)
    dg.boxm("mkt_mezzanine", bx0 + 0.3, bx1 - 0.3, 3.4, by1 - 0.3, 2.6, 2.78, plinth)
    for i, x in enumerate((0.4, 3.5, 6.6)):
        dg.boxm(f"mkt_mezz_post_{i:02d}", x - 0.13, x + 0.13, 3.5, 3.76, 0.57, 2.6, frame)
    dg.boxm("mkt_stair", 6.9, 8.4, 1.5, 3.4, 0.57, 2.6, plinth, chamfer=0.12)
    dg.boxm("mkt_vault", 9.4, 12.6, 3.2, 7.0, 0.0, 3.6, mono, chamfer=0.3,
            corner_segments=2, base_flare=0.24, top_inset=0.14)
    dg.boxm("mkt_vault_hatch", 9.22, 9.44, 4.3, 5.9, 0.0, 2.2, frame)

    # --- shelter pod: stilted, smallest, most portable read ---
    hx0, hx1, hy0, hy1 = 11.5, 16.5, 2.5, 7.0
    for i, (x, y) in enumerate(((hx0 + 0.5, hy0 + 0.5), (hx1 - 0.5, hy0 + 0.5),
                                (hx0 + 0.5, hy1 - 0.5), (hx1 - 0.5, hy1 - 0.5))):
        dg.cylinder(f"hab_stilt_{i:02d}", x, y, -0.1, 0.9, 0.22, frame, segments=10)
    dg.boxm("hab_floor", hx0, hx1, hy0, hy1, 0.82, 0.95, plinth, chamfer=0.1)
    dg.boxm("hab_interior_dark", hx0 + 0.26, hx1 - 0.26, hy0 + 0.26, hy1 - 0.26, 0.95, 0.99,
            dark)
    dg.boxm("hab_wall_back", hx0, hx1, hy1 - 0.26, hy1, 0.95, 3.1, canvas)
    dg.prism("hab_wall_west", [(hy0, 0.95), (hy1, 0.95), (hy1, 3.85), (hy0, 3.1)], "x",
             hx0, hx0 + 0.26, canvas)
    dg.prism("hab_wall_east", [(hy0, 0.95), (hy1, 0.95), (hy1, 3.85), (hy0, 3.1)], "x",
             hx1 - 0.26, hx1, canvas)
    dg.boxm("hab_wall_front_w", hx0, 13.1, hy0, hy0 + 0.26, 0.95, 3.1, canvas)
    dg.boxm("hab_wall_front_e", 14.3, hx1, hy0, hy0 + 0.26, 0.95, 3.1, canvas)
    dg.boxm("hab_lintel", 13.1, 14.3, hy0, hy0 + 0.26, 2.5, 3.1, frame)
    dg.slab_sloped("hab_roof", hx0 - 0.3, hx1 + 0.3, hy0 - 0.45, hy1 + 0.3, 3.15, 3.9, 0.18,
                   zinc)
    dg.boxm("hab_step", 13.1, 14.3, hy0 - 0.75, hy0, 0.0, 0.86, plinth, chamfer=0.1)
    dg.cylinder("hab_cistern", 17.5, 4.4, 0.0, 2.2, 1.0, zinc, segments=16)
    dg.cylinder("hab_cistern_cap", 17.5, 4.4, 2.2, 2.6, 1.0, oxide, segments=16,
                top_radius=0.42)

    # --- ancient: one tilted monolithic slab ---
    slab = dg.boxm("ancient_slab", -4.6, 4.6, -1.3, 1.3, -3.0, 15.0, mono, chamfer=0.3,
                   corner_segments=2, top_inset=0.7)
    slab.location = (0.5, 16.5, 0.0)
    slab.rotation_euler = (math.radians(13.0), 0.0, math.radians(-9.0))
    for i, (x, y, r) in enumerate(((-5.4, 12.4, 1.3), (5.6, 13.2, 0.9), (-2.0, 11.2, 0.7))):
        dg.boxm(f"ancient_shard_{i:02d}", x - r, x + r, y - r, y + r, 0.0, r * 1.35, mono,
                chamfer=r * 0.35, corner_segments=2)

    # --- travel terminal: lattice mast on its own footprint ---
    dg.boxm("travel_pad", 2.4, 4.4, -7.4, -5.8, 0.0, 0.32, plinth, chamfer=0.2,
            corner_segments=2)
    for i, (dx, dy) in enumerate(((-0.55, -0.45), (0.55, -0.45), (-0.55, 0.45),
                                  (0.55, 0.45))):
        dg.cylinder(f"travel_leg_{i:02d}", 3.4 + dx, -6.6 + dy, 0.32, 6.2, 0.09, frame,
                    segments=8)
    for i, z in enumerate((1.6, 3.0, 4.4, 5.6)):
        dg.boxm(f"travel_brace_{i:02d}", 2.75, 4.05, -7.15, -6.05, z, z + 0.1, frame)
    dg.boxm("travel_console", 2.7, 4.1, -5.95, -5.5, 0.32, 1.4, zinc, chamfer=0.1)
    dg.boxm("travel_screen", 2.85, 3.95, -5.99, -5.9, 0.8, 1.32, amber)
    dg.cylinder("travel_beacon", 3.4, -6.6, 6.2, 6.9, 0.3, oxide, segments=12,
                top_radius=0.12)

    proxies = scale_proxies(
        ((-10.5, -1.2), (3.5, -3.4), (13.7, 1.2), (3.4, -8.4), (-4.4, 2.0)),
        dg.mat("C_proxy", "#d7d9d4", rough=0.6),
    )
    return {"name": "c", "label": "Frame Ward", "proxies": proxies,
            "gameplay_target": (3.4, 0.2, 1.0)}


# --------------------------------------------------------------------------
# render harness
# --------------------------------------------------------------------------

BUILDERS = {"a": build_a, "b": build_b, "c": build_c}


def main() -> None:
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else ["a"]
    key = argv[0].lower()
    study = BUILDERS[key]()
    name = study["name"]

    dg.setup_world()
    dg.add_sun(azimuth_deg=215.0, elevation_deg=54.0)
    dg.configure_render(res_x=1600, res_y=900, samples=48)

    wide = dg.add_camera(f"cam_wide_{name}", STUDY_TARGET, STUDY_WIDE_FRUSTUM)
    plan = dg.add_ortho_camera_axis(f"cam_plan_{name}", STUDY_TARGET, "top",
                                   STUDY_PLAN_FRUSTUM)
    play = dg.add_camera(f"cam_play_{name}", study["gameplay_target"],
                         STUDY_GAMEPLAY_FRUSTUM)

    meshes = dg.mesh_objects()
    bounds = dg.world_bounds(meshes)
    tris = dg.triangle_count(meshes)
    print(
        f"[direction {name}] {study['label']}: meshes={len(meshes)} tris={tris} "
        f"materials={len(bpy.data.materials)} bounds={bounds}"
    )

    dg.render_to(proof("directions", f"dir_{name}_wide.png"), wide, 1600, 900)
    dg.render_to(proof("directions", f"dir_{name}_plan.png"), plan, 1200, 1200)
    dg.render_to(proof("directions", f"dir_{name}_gameplay.png"), play, 1280, 720)
    dg.save_blend(proof("blend", f"dustgate_dir_{name}.blend"))


if __name__ == "__main__":
    main()
