#!/usr/bin/env node
import { createHash, randomBytes } from "node:crypto";
import { spawn } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const ORIGIN = "https://www.successorgame.com";
const RELEASE = { client: "standalone-live-client", server: "standalone-live-server", shard: "open-desert" };
const SCHEMA = "successor.standalone-live-runtime-proof.v1";
const DEFAULT_TIMEOUT_MS = 90_000;
const REQUEST_TIMEOUT_MS = 15_000;
const TRANSITION_TIMEOUT_MS = 5_000;
const DEVICE_FLOW_TIMEOUT_MS = 20_000;
const SAFE_ENV_KEYS = new Set(["PATH", "HOME", "USER", "LOGNAME", "TMPDIR", "TMP", "TEMP", "CI", "LANG", "LC_ALL", "TERM", "XDG_CACHE_HOME", "DISPLAY"]);

function sha256(value) { return createHash("sha256").update(value).digest("hex"); }
function canonical(value) { if (Array.isArray(value)) return value.map(canonical); if (value && typeof value === "object") return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])); return value; }
function canonicalJson(value) { return JSON.stringify(canonical(value)); }
function defaultProofPath() { return path.join(process.env.XDG_CACHE_HOME || path.join(os.homedir(), ".cache"), "successor", "standalone-live-runtime-proof.json"); }
function parseArgs(argv) { const args = { out: defaultProofPath(), timeout: DEFAULT_TIMEOUT_MS }; for (let i = 0; i < argv.length; i += 1) { const arg = argv[i]; if (arg === "--out") { const value = argv[++i]; if (!value) throw new Error("--out requires a path"); args.out = value; } else if (arg === "--timeout") args.timeout = Number(argv[++i]); else if (arg === "--help" || arg === "-h") { console.log("usage: node tools/verification/standalone/live-runtime.mjs [--out <proof.json>] [--timeout ms]"); process.exit(0); } else throw new Error(`unknown option ${arg}`); } if (!Number.isInteger(args.timeout) || args.timeout < 15_000) throw new Error("--timeout must be an integer >= 15000"); return args; }
function cleanHeaders(origin = ORIGIN) { return { accept: "application/json", origin, "sec-fetch-site": "same-origin" }; }
function cookiePair(setCookie) { const value = Array.isArray(setCookie) ? setCookie[0] : setCookie; return typeof value === "string" ? value.split(";", 1)[0] : ""; }
function bodyJson(text) { if (!text) return null; try { return JSON.parse(text); } catch { return null; } }
async function reservePort() { const server = net.createServer(); await new Promise((resolve, reject) => { server.once("error", reject); server.listen(0, "127.0.0.1", resolve); }); const port = server.address().port; await new Promise((resolve) => server.close(resolve)); return port; }
function timeout(ms, label) { const error = new Error(`${label} timed out after ${ms}ms`); error.code = "LIVE_RUNTIME_TIMEOUT"; return error; }
async function withTimeout(promise, ms, label) { let timer; try { return await Promise.race([promise, new Promise((_, reject) => { timer = setTimeout(() => reject(timeout(ms, label)), ms); })]); } finally { clearTimeout(timer); } }
async function waitFor(check, ms, label) { const started = Date.now(); while (Date.now() - started < ms) { try { if (await check()) return; } catch { /* startup race */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw timeout(ms, label); }
async function request(base, route, options = {}) { const url = `${base}${route}`; const headers = { ...cleanHeaders(), ...(options.headers ?? {}) }; if (options.body !== undefined) headers["content-type"] = "application/json"; const response = await fetch(url, { method: options.method ?? "GET", headers, body: options.body === undefined ? undefined : JSON.stringify(options.body), redirect: "error", signal: AbortSignal.timeout(options.timeoutMs ?? REQUEST_TIMEOUT_MS) }); const text = await response.text(); return { status: response.status, headers: response.headers, text, json: bodyJson(text), url }; }
function assertStatus(result, expected, label) { if (result.status !== expected) throw new Error(`${label}: expected HTTP ${expected}, got ${result.status}`); return result; }
async function gitOutput(args) { const child = spawn("git", args, { cwd: ROOT, stdio: ["pipe", "pipe", "pipe"] }); const stdout = []; const stderr = []; child.stdout.on("data", (chunk) => stdout.push(chunk)); child.stderr.on("data", (chunk) => stderr.push(chunk)); const code = await withTimeout(new Promise((resolve) => child.once("close", resolve)), 10_000, `git ${args.join(" ")}`); if (code !== 0) throw new Error(`git ${args.join(" ")} failed with exit ${code}`); return Buffer.concat(stdout).toString("utf8").trim(); }
function spawnGroup(command, args, env, cwd = ROOT) { const child = spawn(command, args, { cwd, env, detached: true, stdio: ["pipe", "pipe", "pipe"] }); const stdout = []; const stderr = []; child.stdout.on("data", (chunk) => stdout.push(chunk)); child.stderr.on("data", (chunk) => stderr.push(chunk)); return { child, stdout, stderr, output() { return `${Buffer.concat(stdout).toString("utf8")}\n${Buffer.concat(stderr).toString("utf8")}`; } }; }
async function groupGone(pid) { try { process.kill(-pid, 0); return false; } catch (error) { return error?.code === "ESRCH"; } }
async function stopGroup(group, label) { if (!group?.child?.pid) return true; const pid = group.child.pid; try { process.kill(-pid, "SIGTERM"); } catch (error) { if (error?.code !== "ESRCH") throw error; } let exited = false; try { await withTimeout(new Promise((resolve) => group.child.once("close", () => resolve(true))), 5_000, `${label} exit`); exited = true; } catch { try { process.kill(-pid, "SIGKILL"); } catch (error) { if (error?.code !== "ESRCH") throw error; } } await waitFor(() => groupGone(pid), 5_000, `${label} process group cleanup`); if (!exited) throw new Error(`${label} required SIGKILL`); return true; }
async function childExitCode(group, ms, label) { return withTimeout(new Promise((resolve) => group.child.once("close", resolve)), ms, `${label} exit`); }
function stateRecord(snapshot, characterId) { const actors = Array.isArray(snapshot?.actors) ? snapshot.actors : []; const actor = actors.find((entry) => entry && (entry.id === characterId || entry.actorId === characterId)) ?? actors[0] ?? null; return actor ? canonical(actor) : null; }
function stateHash(snapshot, characterId) { return sha256(canonicalJson(stateRecord(snapshot, characterId))); }
async function joinGame(endpoint, ticket, characterId, label) { const { Client } = await import(pathToFileURL(path.join(ROOT, "client/node_modules/@colyseus/sdk/build/index.mjs")).href); const client = new Client(endpoint, { headers: { Origin: ORIGIN } }); let room; const joinDeadline = Date.now() + (label === "restart" ? 60_000 : 15_000); while (!room) { try { room = await withTimeout(client.joinOrCreate("game", { gameTicket: ticket, release: RELEASE.client }), 15_000, `${label} game join`); } catch (error) { if (label !== "restart" || !String(error?.message ?? error).includes("restore pending") || Date.now() >= joinDeadline) throw error; await new Promise((resolve) => setTimeout(resolve, 250)); } } const hello = await new Promise((resolve, reject) => { const timer = setTimeout(() => { const error = timeout(45_000, `${label} game.hello`); error.liveDiagnostics = diagnostics; reject(error); }, 45_000); room.onMessage("game.packet", (packet) => { if (packet?.type !== "game.hello") return; clearTimeout(timer); resolve(packet); }); room.onError((code, message) => { diagnostics.push({ kind: "error", code, message: String(message ?? "") }); clearTimeout(timer); const error = new Error(`${label} game error ${code}: ${message ?? "unknown"}`); error.liveDiagnostics = diagnostics; reject(error); }); room.send("game.ready", { areaId: RELEASE.shard, x: 512, y: 513, radiusCells: 192 }); }); return { room, hello }; }
async function joinChat(endpoint, ticket, label) { const wsModule = await import(pathToFileURL(path.join(ROOT, "client-tui/node_modules/ws/index.js")).href); const WebSocket = wsModule.default ?? wsModule.WebSocket; const socket = new WebSocket(endpoint, { headers: { Origin: ORIGIN } }); const hello = await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(timeout(10_000, `${label} chat.hello`)), 10_000); socket.on("error", (error) => { clearTimeout(timer); reject(error); }); socket.on("open", () => socket.send(JSON.stringify({ type: "chat.authenticate", chatTicket: ticket, release: RELEASE.client }))); socket.on("message", (data) => { try { const packet = JSON.parse(String(data)); if (packet?.type === "chat.hello") { clearTimeout(timer); resolve(packet); } } catch { /* ignore non-json */ } }); }); return { socket, hello }; }
async function closeRoom(room) { if (!room) return; await withTimeout(room.leave(true), 3_000, "room close").catch(() => undefined); }
async function closeSocket(socket) { if (!socket || socket.readyState === 3) return; await withTimeout(new Promise((resolve) => { socket.once("close", resolve); socket.close(1000, "standalone live smoke done"); }), 1_000, "socket close").catch(() => undefined); }
async function fileHash(file) { try { return sha256(await readFile(file)); } catch (error) { if (error.code === "ENOENT") return null; throw error; } }
async function durableHashes(stateDir, shardId) { return { character: await fileHash(path.join(stateDir, "characters.json")), checkpoint: await fileHash(path.join(stateDir, `${shardId}.checkpoint.json`)), journal: await fileHash(path.join(stateDir, `${shardId}.journal.jsonl`)), manifest: await fileHash(path.join(stateDir, "state-generation.manifest.json")) }; }
function scanSecrets(secrets, values) { const needles = [...new Set(secrets.filter((value) => typeof value === "string" && value.length >= 4))]; const hits = []; for (const [label, value] of values) for (const needle of needles) if (String(value).includes(needle)) hits.push(label); return { ok: hits.length === 0, hits: [...new Set(hits)] }; }
function spawnHostedTui({ credentialState, characterId, loopbackBase }) { const cliUrl = pathToFileURL(path.join(ROOT, "client-tui/dist/cli.js")).href; const script = `
    const origin = ${JSON.stringify(ORIGIN)};
    const loopback = ${JSON.stringify(loopbackBase)};
    const upstreamFetch = globalThis.fetch;
    globalThis.fetch = async (url, init = {}) => {
      const source = String(url);
      const rewritten = source.startsWith(origin) ? loopback + source.slice(origin.length) : source;
      const headers = new Headers(init.headers);
      headers.set("origin", origin);
      return upstreamFetch(rewritten, { ...init, headers, signal: AbortSignal.timeout(5000) });
    };
    const { main } = await import(${JSON.stringify(cliUrl)});
    process.exitCode = await main(["--plain", "--character", ${JSON.stringify(characterId)}]);
  `; const env = { ...Object.fromEntries(Object.entries(process.env).filter(([key]) => SAFE_ENV_KEYS.has(key))), CI: "1", TERM: "dumb", XDG_STATE_HOME: credentialState }; return spawnGroup(process.execPath, ["--input-type=module", "-e", script], env); }

async function main() {
  const args = parseArgs(process.argv.slice(2)); const startedAt = Date.now(); const out = path.resolve(args.out ?? path.join(process.env.XDG_CACHE_HOME ?? path.join(os.homedir(), ".cache"), "successor", "standalone-live-runtime-proof.json")); await mkdir(path.dirname(out), { recursive: true }); const cacheRoot = path.join(path.dirname(out), `.standalone-live-${process.pid}-${randomBytes(8).toString("hex")}`); const stateDir = path.join(cacheRoot, "state"); const credentialState = path.join(cacheRoot, "tui-state"); await mkdir(stateDir, { recursive: true, mode: 0o700 }); const secrets = []; const issuedUrls = []; const capturedSurfaces = []; let server; let deviceGame; let deviceChat; let browserGame; let browserChat; let clean = false; let processCleanup = false; const timings = {}; const mark = (name, at) => { timings[name] = Math.max(0, at - startedAt); };
  try {
    const port = await reservePort(); const base = `http://127.0.0.1:${port}`; const gameEndpoint = `ws://127.0.0.1:${port}`; const chatEndpoint = `${gameEndpoint}/chat/ws`; issuedUrls.push(base, gameEndpoint, chatEndpoint); const dbPath = path.join(stateDir, "control.sqlite"); const claimSecret = randomBytes(32).toString("hex"); secrets.push(claimSecret); const alpha = await import(pathToFileURL(path.join(ROOT, "server/dist/alpha/index.js")).href); const bootstrapStore = new alpha.AlphaControlStore({ dbPath, claimSecret: Buffer.from(claimSecret, "hex"), registrationOpen: true }); const controlHead = bootstrapStore.schemaHead(); bootstrapStore.close(); mark("bootstrapControlDb", Date.now());
    const childEnv = { ...Object.fromEntries(Object.entries(process.env).filter(([key]) => SAFE_ENV_KEYS.has(key))), NODE_ENV: "development", HOST: "127.0.0.1", PORT: String(port), CI: "1", SUCCESSOR_CONTROL_PLANE_MODE: "standalone", ALPHA_CONTROL_DB_PATH: dbPath, ALPHA_CONTROL_CLAIM_SECRET: claimSecret, SUCCESSOR_ALPHA_ORIGIN: ORIGIN, SUCCESSOR_ALPHA_CLIENT_ORIGIN: ORIGIN, SUCCESSOR_ALPHA_GAME_ENDPOINT: gameEndpoint, SUCCESSOR_ALPHA_CHAT_ENDPOINT: chatEndpoint, SUCCESSOR_ALPHA_REGISTRATION_OPEN: "true", SUCCESSOR_ALPHA_CLIENT_RELEASE_ALLOWLIST: RELEASE.client, SUCCESSOR_CLIENT_RELEASE_ID: RELEASE.client, SUCCESSOR_SERVER_RELEASE_ID: RELEASE.server, SUCCESSOR_SHARD_ID: RELEASE.shard, SUCCESSOR_LAUNCH_ISSUER: "standalone-live-smoke", GAME_SHARD_PERSISTENCE: "1", GAME_SHARD_STATE_DIR: stateDir, GAME_SHARD_CHECKPOINT_INTERVAL_MS: "500", GAME_CHARACTER_CHECKPOINT_SECONDS: "1", GAME_SNAPSHOT_INTERVAL_MS: "20", SUCCESSOR_ALPHA_LEGAL_VERSIONS: "{}", LOG_LEVEL: "info" }; server = spawnGroup(process.execPath, [path.join(ROOT, "server/dist/index.js")], childEnv); try { await waitFor(async () => (await request(base, "/healthz", { timeoutMs: TRANSITION_TIMEOUT_MS })).status === 200, args.timeout, "server startup"); } catch (error) { await writeFile(path.join(cacheRoot, "server-startup-failure.json"), JSON.stringify({ error: String(error), endpoint: "/healthz", child: { exitCode: server?.child.exitCode ?? null, signal: server?.child.signalCode ?? null }, output: server?.output().replace(/[A-Za-z0-9_-]{20,}/g, "[redacted]") ?? "" }, null, 2)); throw error; } try { await waitFor(async () => (await request(base, "/readyz", { timeoutMs: TRANSITION_TIMEOUT_MS })).status === 200, args.timeout, "server readiness"); } catch (error) { await writeFile(path.join(cacheRoot, "server-startup-failure.json"), JSON.stringify({ error: String(error), endpoint: "/readyz", child: { exitCode: server?.child.exitCode ?? null, signal: server?.child.signalCode ?? null }, output: server?.output().replace(/[A-Za-z0-9_-]{20,}/g, "[redacted]") ?? "" }, null, 2)); throw error; } mark("serverReady", Date.now());
    const browserPassword = `pw-${randomBytes(16).toString("hex")}`; secrets.push(browserPassword); const callsign = `live_${process.pid.toString(36)}`; const csrf = assertStatus(await request(base, "/alpha-api/csrf"), 200, "csrf"); const browserPreCookie = cookiePair(csrf.headers.getSetCookie?.() ?? csrf.headers.get("set-cookie")); secrets.push(browserPreCookie, csrf.json.csrfToken); const registered = assertStatus(await request(base, "/alpha-api/register", { method: "POST", headers: { ...cleanHeaders(), cookie: browserPreCookie, "x-csrf-token": csrf.json.csrfToken }, body: { callsign, password: browserPassword } }), 201, "register"); const browserCookie = cookiePair(registered.headers.getSetCookie?.() ?? registered.headers.get("set-cookie")); secrets.push(browserCookie); assertStatus(await request(base, "/alpha-api/session", { headers: { ...cleanHeaders(), cookie: browserCookie } }), 200, "session"); const freshCsrf = assertStatus(await request(base, "/alpha-api/csrf", { headers: { ...cleanHeaders(), cookie: browserCookie } }), 200, "csrf refresh"); secrets.push(freshCsrf.json.csrfToken); const created = assertStatus(await request(base, "/alpha-api/characters", { method: "POST", headers: { ...cleanHeaders(), cookie: browserCookie, "x-csrf-token": freshCsrf.json.csrfToken }, body: { name: "LiveSmoke", appearance: { skinTone: "#c78f62", hair: "hair_mop", hairMat: "hair_raven", face: null }, initialProfessionId: "scout" } }), 201, "character create"); const characterId = created.json.id; const roster = assertStatus(await request(base, "/alpha-api/characters", { headers: { ...cleanHeaders(), cookie: browserCookie } }), 200, "character list"); const browserTicket = assertStatus(await request(base, "/alpha-api/play-ticket", { method: "POST", headers: { ...cleanHeaders(), cookie: browserCookie, "x-csrf-token": freshCsrf.json.csrfToken }, body: { characterId } }), 200, "browser play-ticket"); const browserGameTicket = browserTicket.json.gameTicket; const browserChatTicket = browserTicket.json.chatTicket; secrets.push(browserGameTicket, browserChatTicket); issuedUrls.push(browserTicket.url); const wrongOrigin = await request(base, "/alpha-api/register", { method: "POST", headers: { ...cleanHeaders("https://evil.example.invalid"), cookie: browserCookie, "x-csrf-token": freshCsrf.json.csrfToken }, body: { callsign: "bad_origin", password: browserPassword } }); if (wrongOrigin.status !== 403) throw new Error(`wrong Origin was accepted (${wrongOrigin.status})`); browserGame = await joinGame(gameEndpoint, browserGameTicket, characterId, "browser"); browserChat = await joinChat(chatEndpoint, browserChatTicket, "browser"); const browserStateHash = stateHash(browserGame.hello.snapshot, characterId); mark("browserReady", Date.now());
    let replayTimedOut = false; let replayResponse; try { replayResponse = await request(base, "/matchmake/joinOrCreate/game", { method: "POST", timeoutMs: TRANSITION_TIMEOUT_MS, headers: { ...cleanHeaders(), "content-type": "application/json" }, body: { gameTicket: browserGameTicket } }); } catch (error) { if (error?.name === "TimeoutError" || error?.name === "AbortError" || error?.code === "ABORT_ERR") replayTimedOut = true; else throw error; } const ticketReplayRejected = replayTimedOut || replayResponse?.status >= 400; if (!ticketReplayRejected) throw new Error("replayed game ticket was accepted");
    const deviceDeadline = Date.now() + DEVICE_FLOW_TIMEOUT_MS; const transition = (route, options) => request(base, route, { ...options, timeoutMs: TRANSITION_TIMEOUT_MS }); const deviceStart = assertStatus(await transition("/alpha-api/device/start", { method: "POST", headers: { ...cleanHeaders(), "content-type": "application/json" }, body: { clientId: "successor-tui", releaseId: RELEASE.client, scopes: ["character:list", "play-ticket"] } }), 201, "device start"); const deviceCode = deviceStart.json.deviceCode; const userCode = deviceStart.json.userCode; secrets.push(deviceCode, userCode); const decision = await transition("/alpha-api/device/decision", { method: "POST", headers: { ...cleanHeaders(), cookie: browserCookie, "x-csrf-token": freshCsrf.json.csrfToken }, body: { userCode, decision: "approve" } }); assertStatus(decision, 204, "device browser approval"); let credential; for (let attempt = 0; attempt < 12 && !credential; attempt += 1) { if (Date.now() >= deviceDeadline) throw timeout(DEVICE_FLOW_TIMEOUT_MS, "device exchange"); const poll = assertStatus(await transition("/alpha-api/device/poll", { method: "POST", headers: { ...cleanHeaders(), "content-type": "application/json" }, body: { deviceCode } }), 200, "device poll"); if (poll.json.status === "exchanged") credential = poll.json.credential; if (!credential) await new Promise((resolve) => setTimeout(resolve, Math.min(250, Math.max(1, deviceDeadline - Date.now())))); } if (!credential) throw timeout(DEVICE_FLOW_TIMEOUT_MS, "device exchange"); secrets.push(credential); const authHeader = { ...cleanHeaders(), authorization: `Bearer ${credential}` }; const deviceRoster = assertStatus(await request(base, "/alpha-api/characters", { headers: authHeader }), 200, "TUI roster"); if (deviceRoster.json.characters?.length !== 1 || deviceRoster.json.characters[0]?.id !== characterId) throw new Error("device roster did not preserve exact character"); const pendingTicket = assertStatus(await request(base, "/alpha-api/play-ticket", { method: "POST", headers: { ...authHeader, "content-type": "application/json" }, body: { characterId } }), 200, "pending device ticket"); const activeTicket = assertStatus(await request(base, "/alpha-api/play-ticket", { method: "POST", headers: { ...authHeader, "content-type": "application/json" }, body: { characterId } }), 200, "active device ticket"); secrets.push(pendingTicket.json.gameTicket, pendingTicket.json.chatTicket, activeTicket.json.gameTicket, activeTicket.json.chatTicket); deviceGame = await joinGame(activeTicket.json.endpoints.game, activeTicket.json.gameTicket, characterId, "device"); deviceChat = await joinChat(activeTicket.json.endpoints.chat, activeTicket.json.chatTicket, "device"); mark("deviceReady", Date.now());
    await mkdir(path.join(credentialState, "successor"), { recursive: true, mode: 0o700 }); await writeFile(path.join(credentialState, "successor", "credential.json"), `${JSON.stringify({ schema: "successor.tui-credential.v1", apiUrl: ORIGIN, credential, scopes: ["character:list", "play-ticket"], obtainedAt: new Date().toISOString() }, null, 2)}\n`, { mode: 0o600 }); const tui = spawnHostedTui({ credentialState, characterId, loopbackBase: base }); try { await waitFor(() => tui.output().includes("Signal locked"), 20_000, "TUI game readiness"); } catch (error) { await writeFile(path.join(cacheRoot, "tui-readiness-failure.json"), JSON.stringify({ error: String(error), output: tui.output().replace(/[A-Za-z0-9_-]{20,}/g, "[redacted]"), phase: { browser: true, device: true, tuiStarted: true, tuiReady: false } }, null, 2)); await stopGroup(tui, "TUI readiness timeout").catch(() => undefined); throw error; } if (tui.child.stdin?.writable) tui.child.stdin.end("/quit\n"); let tuiCode; try { tuiCode = await childExitCode(tui, 15_000, "TUI hosted/headless"); } catch (error) { await stopGroup(tui, "TUI hosted/headless timeout").catch(() => undefined); capturedSurfaces.push(["tui-output", tui.output()]); throw error; } capturedSurfaces.push(["tui-output", tui.output()]); if (tuiCode !== 0) throw new Error(`TUI hosted/headless path failed with ${tuiCode}`); await waitFor(() => groupGone(tui.child.pid), 5_000, "TUI process group cleanup"); mark("tuiReady", Date.now());
    const revoke = await transition("/alpha-api/device/logout", { method: "POST", headers: { ...cleanHeaders(), authorization: `Bearer ${credential}` } }); assertStatus(revoke, 204, "device revoke"); await waitFor(() => deviceGame.room.connection?.isOpen === false || deviceGame.room.connection?.ws?.readyState === 3, 10_000, "device game revoke close").catch(() => undefined); await waitFor(() => deviceChat.socket.readyState === 3, 10_000, "device chat revoke close").catch(() => undefined); const pendingRejectedResponse = await transition("/matchmake/joinOrCreate/game", { method: "POST", headers: { ...cleanHeaders(), "content-type": "application/json" }, body: { gameTicket: pendingTicket.json.gameTicket } }); const pendingTicketRejected = pendingRejectedResponse.status >= 400; if (!pendingTicketRejected) throw new Error("pending device ticket survived revocation"); const deviceGameClosed = deviceGame.room.connection?.isOpen === false || deviceGame.room.connection?.ws?.readyState === 3; const deviceChatClosed = deviceChat.socket.readyState === 3; if (!deviceGameClosed || !deviceChatClosed) throw new Error("device sessions stayed open after revocation"); await closeRoom(deviceGame.room); await closeSocket(deviceChat.socket); await closeRoom(browserGame.room); await closeSocket(browserChat.socket); browserGame = undefined; browserChat = undefined;
    await new Promise((resolve) => setTimeout(resolve, 1_500)); const beforeRestartHashes = await durableHashes(stateDir, RELEASE.shard); const beforeRestartRoster = roster.json.characters; capturedSurfaces.push(["server-output-before-restart", server.output()]); await stopGroup(server, "server"); server = undefined; const restarted = spawnGroup(process.execPath, [path.join(ROOT, "server/dist/index.js")], childEnv); server = restarted; await waitFor(async () => (await request(base, "/healthz", { timeoutMs: TRANSITION_TIMEOUT_MS })).status === 200, args.timeout, "server restart"); await waitFor(async () => (await request(base, "/readyz", { timeoutMs: TRANSITION_TIMEOUT_MS })).status === 200, args.timeout, "server restart readiness"); assertStatus(await request(base, "/alpha-api/session", { headers: { ...cleanHeaders(), cookie: browserCookie } }), 200, "persisted browser session"); const persistedRosterResponse = assertStatus(await request(base, "/alpha-api/characters", { headers: { ...cleanHeaders(), cookie: browserCookie } }), 200, "persisted roster"); const afterRoster = persistedRosterResponse.json.characters; if (afterRoster.length !== 1 || afterRoster[0].id !== characterId || afterRoster[0].worldEntryClaimed !== true) throw new Error("restart duplicated or lost starter character state"); const restartCsrf = assertStatus(await request(base, "/alpha-api/csrf", { headers: { ...cleanHeaders(), cookie: browserCookie } }), 200, "restart csrf"); let restartTicket; let restartedGame; let restartedChat;
    for (let attempt = 0; attempt < 20 && !restartedGame; attempt += 1) {
      restartTicket = assertStatus(await request(base, "/alpha-api/play-ticket", { method: "POST", headers: { ...cleanHeaders(), cookie: browserCookie, "x-csrf-token": restartCsrf.json.csrfToken }, body: { characterId } }), 200, "restart play-ticket");
      secrets.push(restartTicket.json.gameTicket, restartTicket.json.chatTicket);
      try {
        restartedGame = await joinGame(restartTicket.json.endpoints.game, restartTicket.json.gameTicket, characterId, "restart");
        restartedChat = await joinChat(restartTicket.json.endpoints.chat, restartTicket.json.chatTicket, "restart");
      } catch (error) {
        if (!String(error?.message ?? error).includes("onAuth failed") && !String(error?.message ?? error).includes("restore pending")) throw error;
        await new Promise((resolve) => setTimeout(resolve, 250));
      }
    }
    if (!restartedGame || !restartedChat) throw timeout(60_000, "restart fresh browser rejoin");
    const restartActor = stateRecord(restartedGame.hello.snapshot, characterId);
    const restartPlayerActorId = restartedGame.hello.playerActorId ?? restartedGame.hello.snapshot?.playerActorId ?? null;
    const restartCheckpoint = JSON.parse(await readFile(path.join(stateDir, `${RELEASE.shard}.checkpoint.json`), "utf8"));
    const durableActor = restartCheckpoint.rustAuthority?.state?.state?.actors?.[characterId] ?? null;
    if (!restartActor && !(restartPlayerActorId === characterId && durableActor)) {
      await writeFile(path.join(cacheRoot, "restart-actor-diagnostic.json"), JSON.stringify({
        characterId,
        playerActorId: restartPlayerActorId,
        durableActorPresent: Boolean(durableActor),
        actorIds: Array.isArray(restartedGame.hello.snapshot?.actors)
          ? restartedGame.hello.snapshot.actors.map((actor) => ({ id: actor.id, actorId: actor.actorId, areaId: actor.areaId }))
          : [],
      }, null, 2));
      throw new Error("restart world entry did not hydrate the durable actor");
    }
    const afterRestartStateHash = stateHash(restartedGame.hello.snapshot, characterId);
    await closeRoom(restartedGame.room);
    await closeSocket(restartedChat.socket);
    const afterRestartHashes = await durableHashes(stateDir, RELEASE.shard);
    mark("restartReady", Date.now());
    if (!beforeRestartHashes.character || !afterRestartHashes.character) throw new Error("durable character evidence missing");
    capturedSurfaces.push(["server-output-after-restart", server.output()]);
    await stopGroup(server, "final server cleanup");
    server = undefined;
    processCleanup = true;
    const proof = { schema: SCHEMA, publishable: false, desktopLive: false, release: RELEASE, source: { commit: await gitOutput(["rev-parse", "HEAD"]), tree: await gitOutput(["rev-parse", "HEAD^{tree}"]) }, characterId, checks: { browser: true, tuiHostedHeadless: true, rustAuthority: true, colyseus: true, chat: true, wrongOriginRejected: true, ticketReplayRejected, replayTransitionTimedOut: replayTimedOut, deviceFlow: true, pendingTicketRejected, activeGameSessionClosed: deviceGameClosed, activeChatSessionClosed: deviceChatClosed, restartPersistence: true, rosterPersistence: true, worldEntryPersistence: true, actorPersistence: true, freshBrowserRejoin: true, processCleanup }, stateHashes: { browserHello: browserStateHash, beforeRestart: beforeRestartHashes, afterRestart: afterRestartHashes, restartHello: afterRestartStateHash }, roster: { beforeRestart: beforeRestartRoster, afterRestart: afterRoster }, controlSchemaHead: controlHead, timingsMs: timings, limitations: ["desktopLive:false: packaged Electron was not run; server/browser/TUI/Rust proof is real and publishable remains false", "loopback HTTP/ws transport used only for this local proof; every client presented the exact HTTPS storefront Origin", "TUI credential storage retained the canonical HTTPS site apiUrl while its injected transport rewrote requests to loopback"], secretScan: { ok: false, hits: [] } }; capturedSurfaces.push(["proof", JSON.stringify(proof)]); const scan = scanSecrets(secrets, [["argv", process.argv.join(" ")], ["parent-env", Object.entries(process.env).filter(([key]) => key !== "ALPHA_CONTROL_CLAIM_SECRET").flat().join(" ")], ["urls", issuedUrls.join(" ")], ...capturedSurfaces]); proof.secretScan = scan; if (!scan.ok) throw new Error(`issued secret appeared in ${scan.hits.join(",")}`); const proofText = `${JSON.stringify(proof, null, 2)}\n`; const digest = sha256(canonicalJson(proof)); await writeFile(out, proofText, "utf8"); await writeFile(`${out}.sha256`, `${digest}  ${path.basename(out)}\n`, "utf8"); clean = true; return { proof, digest };
  } finally { await closeRoom(browserGame?.room); await closeSocket(browserChat?.socket); await closeRoom(deviceGame?.room); await closeSocket(deviceChat?.socket); if (server) await stopGroup(server, "server cleanup").catch(() => undefined); if (clean) await rm(cacheRoot, { recursive: true, force: true }).catch(() => undefined); }
}
main().then(({ proof, digest }) => { const output = { schema: SCHEMA, status: "pass", proof: process.argv.includes("--out") ? path.resolve(process.argv[process.argv.indexOf("--out") + 1]) : path.resolve(defaultProofPath()), proofDigest: digest, timingsMs: proof.timingsMs, desktopLive: proof.desktopLive }; process.stdout.write(`${JSON.stringify(output)}\n`); }).catch((error) => { process.stderr.write(`${error instanceof Error ? error.stack ?? error.message : String(error)}\n`); process.exitCode = 1; });
