#!/usr/bin/env node
import { createHash } from "node:crypto";
import { spawn } from "node:child_process";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createLocalSourceIdentity } from "../farm/source-hash.mjs";
import { repoRoot } from "../farm/common.mjs";
export const STANDALONE_MATRIX_SCHEMA = "successor.verify-standalone-matrix.v1";
export const TASK_METADATA_SCHEMA = "successor.verify-standalone-task-metadata.v1";
export const MAX_CONCURRENCY = 4;
export const DEFAULT_TIMEOUT_MS = 15 * 60 * 1000;
const EMPTY_SHA256 = createHash("sha256").update("").digest("hex");
const SECRET_VALUE = /(?:bearer\s+)[A-Za-z0-9._~+/=-]+|(?:eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)|(?:-----BEGIN [A-Z ]+ KEY-----)[\s\S]*?(?:-----END [A-Z ]+ KEY-----)/giu;
const KEY_VALUE = /(\b(?:token|secret|password|passwd|api[_-]?key|authorization|credential)\b\s*[=:]\s*["']?)([^\s"',;]+)/giu;
export const sha256 = (value) => createHash("sha256").update(value).digest("hex");
export function canonicalize(value) { if (Array.isArray(value)) return value.map(canonicalize); if (value && typeof value === "object") return Object.fromEntries(Object.keys(value).sort(byteCompare).map((key) => [key, canonicalize(value[key])])); return value; }
export function canonicalJson(value) { return JSON.stringify(canonicalize(value)); }
export function redactOutput(value, secrets = []) { let text = String(value ?? ""); for (const secret of secrets.filter((secret) => typeof secret === "string" && secret.length >= 4).sort((a, b) => b.length - a.length)) text = text.split(secret).join("[REDACTED]"); text = text.replace(SECRET_VALUE, "[REDACTED]"); return text.replace(KEY_VALUE, "$1[REDACTED]"); }
export function hasUnredactedSecret(value) { const text = String(value ?? ""); SECRET_VALUE.lastIndex = 0; return SECRET_VALUE.test(text) || /\b(?:token|secret|password|api[_-]?key|authorization)\b\s*[=:]\s*(?!\[REDACTED\])[^\s"',;]+/iu.test(text); }
function safeEnv() { const allowed = new Set(["PATH", "HOME", "USER", "LOGNAME", "TMPDIR", "TMP", "TEMP", "CI", "LANG", "LC_ALL", "TERM", "XDG_CACHE_HOME", "DISPLAY"]); const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => allowed.has(key))); env.CI = "1"; return env; }
function killGroup(child, signal) { if (!child?.pid) return; try { process.kill(-child.pid, signal); } catch { try { child.kill(signal); } catch {} } }
export function runCommand(command, args = [], { cwd = repoRoot, timeoutMs = DEFAULT_TIMEOUT_MS, signal, secrets = [], env = {} } = {}) { return new Promise((resolve) => { const started = Date.now(); const child = spawn(command, args, { cwd, env: { ...safeEnv(), ...env }, detached: true, stdio: ["ignore", "pipe", "pipe"] }); const stdout = []; const stderr = []; let timedOut = false; let aborted = false; let spawnError; const terminate = () => { killGroup(child, "SIGTERM"); setTimeout(() => killGroup(child, "SIGKILL"), 1_500).unref(); }; const onAbort = () => { aborted = true; terminate(); }; signal?.addEventListener("abort", onAbort, { once: true }); if (signal?.aborted) onAbort(); const timer = timeoutMs > 0 ? setTimeout(() => { timedOut = true; terminate(); }, timeoutMs) : undefined; timer?.unref(); child.stdout.on("data", (chunk) => stdout.push(chunk)); child.stderr.on("data", (chunk) => stderr.push(chunk)); child.on("error", (error) => { spawnError = error; }); child.on("close", (exitCode, childSignal) => { clearTimeout(timer); signal?.removeEventListener("abort", onAbort); const redactedStdout = redactOutput(Buffer.concat(stdout).toString("utf8"), secrets); const redactedStderr = redactOutput(Buffer.concat(stderr).toString("utf8"), secrets); const outputSafe = !hasUnredactedSecret(redactedStdout) && !hasUnredactedSecret(redactedStderr); resolve({ command, args, exitCode, signal: childSignal, timedOut, aborted, error: spawnError, durationMs: Date.now() - started, stdout: redactedStdout, stderr: redactedStderr, outputSafe, ok: exitCode === 0 && !timedOut && !aborted && !spawnError && outputSafe }); }); }); }
export async function artifactDigest(root, relativePath) { const absolute = path.resolve(root, relativePath); try { const info = await stat(absolute); if (info.isFile()) { const data = await readFile(absolute); return { path: relativePath, bytes: data.byteLength, sha256: sha256(data) }; } if (!info.isDirectory()) return { path: relativePath, bytes: 0, sha256: EMPTY_SHA256, present: false }; const entries = []; async function walk(directory, prefix) { const { readdir } = await import("node:fs/promises"); for (const item of (await readdir(directory, { withFileTypes: true })).sort((a, b) => byteCompare(a.name, b.name))) { const child = path.join(directory, item.name); const childPath = prefix ? `${prefix}/${item.name}` : item.name; if (item.isDirectory()) await walk(child, childPath); else if (item.isFile()) { const data = await readFile(child); entries.push({ path: childPath, bytes: data.byteLength, sha256: sha256(data) }); } } } await walk(absolute, ""); return { path: relativePath, bytes: entries.reduce((sum, entry) => sum + entry.bytes, 0), sha256: sha256(canonicalJson(entries)), entries }; } catch (error) { if (error?.code === "ENOENT") return { path: relativePath, bytes: 0, sha256: EMPTY_SHA256, present: false }; throw error; } }
export async function collectArtifacts(root, paths, logDir, stdout, stderr) { await mkdir(logDir, { recursive: true }); await writeFile(path.join(logDir, "stdout.log"), stdout, "utf8"); await writeFile(path.join(logDir, "stderr.log"), stderr, "utf8"); const records = []; for (const artifactPath of [...paths, path.relative(root, path.join(logDir, "stdout.log")), path.relative(root, path.join(logDir, "stderr.log"))]) records.push(await artifactDigest(root, artifactPath)); return records; }
export async function gitStatus(root) { const result = await runCommand("git", ["status", "--porcelain", "--untracked-files=all"], { cwd: root, timeoutMs: 30_000 }); if (!result.ok) throw new Error(`git status failed: ${result.stderr || result.error?.message || result.exitCode}`); return result.stdout.split(/\r?\n/u).filter(Boolean); }
export async function sourceIdentity(root = repoRoot) { const status = await gitStatus(root); if (status.length) { const error = new Error(`standalone verification requires a clean source tree (${status.length} change(s))`); error.code = "DIRTY_SOURCE"; error.details = { status }; throw error; } const identity = await createLocalSourceIdentity({ root, includeManifest: true }); const commit = await gitOutput(root, ["rev-parse", "HEAD"]); const tree = await gitOutput(root, ["rev-parse", "HEAD^{tree}"]); return { commit, tree, ...identity }; }
export async function gitOutput(root, args) { const result = await runCommand("git", args, { cwd: root, timeoutMs: 30_000 }); if (!result.ok) throw new Error(`git ${args.join(" ")} failed: ${result.stderr || result.exitCode}`); return result.stdout.trim(); }
export function taskDigest(task) { return sha256(canonicalJson(task)); }
export function validateMatrix(matrix) { if (!matrix || matrix.schema !== STANDALONE_MATRIX_SCHEMA) throw new Error("standalone matrix schema mismatch"); if (!matrix.source?.commit || !matrix.source?.tree || !matrix.source?.sourceHash || !matrix.source?.manifest) throw new Error("standalone matrix source binding missing"); if (!Array.isArray(matrix.tasks) || matrix.tasks.length === 0) throw new Error("standalone matrix task list missing"); const ids = matrix.tasks.map((task) => task.id); if (new Set(ids).size !== ids.length || ids.some((id, index) => id !== [...ids].sort(byteCompare)[index])) throw new Error("standalone matrix task ordering is not deterministic"); for (const task of matrix.tasks) { if (!task.command || !task.status || typeof task.durationMs !== "number" || !task.digest || !Array.isArray(task.artifacts)) throw new Error(`task ${task.id} is incomplete`); for (const artifact of task.artifacts) if (typeof artifact.path !== "string" || typeof artifact.bytes !== "number" || !/^[a-f0-9]{64}$/u.test(artifact.sha256)) throw new Error(`task ${task.id} has an invalid artifact`); } return true; }
function byteCompare(left, right) { return Buffer.compare(Buffer.from(left, "utf8"), Buffer.from(right, "utf8")); }
